### ISSUE TITLE
Install this plugin?

### ISSUE THREAD

**Issue by coollittlestoaster** [kuestess/homebridge-platform-insteonlocal#1]
Forgive the dumb question, but how do I install this plugin locally since it is not in npm? Thanks

**Comment by kuestess** [comment]
You can clone the repo or download and unzip, then cd into the directory where you unzipped/cloned and run 'npm -g install' (without the quotes; you may need to add sudo to that command depending upon your installation).  This version only supports a single device, but I should have an updated version that supports multiple devices soon.

**Comment by coollittlestoaster** [comment]
I knew it was that simple! Thanks so much for the quick reply and help. Right now, I am just trying to get my I/O Linc connected through my hub, so single device should work just fine. I installed it and added my config file, but I am now getting this error: 
```
[2018-1-3 12:38:30] ====================
[2018-1-3 12:38:30] ERROR LOADING PLUGIN homebridge-platform-insteonlocal:
[2018-1-3 12:38:30] Error: Cannot find module 'sync-request'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.Module._load (module.js:472:25)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pi/Temporary Items/homebridge-platform-insteonlocal/index.js:3:15)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
[2018-1-3 12:38:30] ====================
```
Am I missing a sync-request plugin or something like that, do you happen to know? Thanks again for your help!

**Comment by kuestess** [comment]
Sorry, I messed up the package.json.  Run 'npm -g install sync-request' and that should fix it.  Btw, this is really designed for lighting/dimmers, but you should be able to trigger the relay on the IOlinc with an open/close.  Sensor status might take a bit more work.

**Comment by coollittlestoaster** [comment]
Awesome, thanks so much
