### ISSUE TITLE
Hoobs Install Error

### ISSUE THREAD

**Issue by ndejong5** [kuestess/homebridge-platform-insteonlocal#120]
I can't get the plugin to install properly on my Hoobs system.

11/18/2020, 2:06:49 PM [InsteonLocal] Initializing InsteonLocal platform...
11/18/2020, 2:06:49 PM Initializing Insteon UI
11/18/2020, 2:06:49 PM Reading config from /home/hoobs/.hoobs/etc/config.json
11/18/2020, 2:06:49 PM Found 2 platform(s) in config
11/18/2020, 2:06:49 PM Creating new insteon.json
11/18/2020, 2:06:49 PM No devices in config
11/18/2020, 2:06:49 PM TypeError: Cannot read property 'length' of undefined
    at new InsteonLocalPlatform (/home/hoobs/.hoobs/node_modules/homebridge-platform-insteonlocal/index.js:292:35)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:346:30
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:320:31)
    at Server.start (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:152:35)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:94:16
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
11/18/2020, 2:06:49 PM Got SIGTERM, shutting down Bridge...

**Comment by ndejong5** [comment]
Once I added a device it ran.
