### ISSUE TITLE
Insteonlocal install prevents bridge service from starting

### ISSUE THREAD

**Issue by petrcassid** [kuestess/homebridge-platform-insteonlocal#129]
I have HOOBS 3.3.1 running on a Pi4B. Works fine with 2 plugins. When I install insteonlocal bridge service won't start. Error log says no devices configured. I tried accessing InsteonUI to configure a device (which was a solution I saw elsewhere on this list), but Insteon UI does not appear to be running on Pi4B. Here is the log file

12/22/2020, 10:09:42 AM Initializing Insteon UI
12/22/2020, 10:09:42 AM Reading config from /home/hoobs/.hoobs/etc/config.json
12/22/2020, 10:09:42 AM Found 3 platform(s) in config
12/22/2020, 10:09:42 AM Creating new insteon.json
12/22/2020, 10:09:42 AM No devices in config
12/22/2020, 10:09:42 AM TypeError: Cannot read property 'length' of undefined
    at new InsteonLocalPlatform (/home/hoobs/.hoobs/node_modules/homebridge-platform-insteonlocal/index.js:292:19)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:346:30
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:320:31)
    at Server.start (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:152:35)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:94:16
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by kuestess** [comment]
@petrcassid This error means that you don't have any Insteon devices defined in your config.json.  Can you let me know what version of the plugin HOOBS says is installed?  I recently made an update that fixed the crash when no devices were defined.  I want to remember that HOOBS only applies updates when releases are made - my workflow to automatically publish releases apparently stopped working, so it may not have the latest update.  I just published a release manually, so please check to see if an update to the plugin is available in HOOBS.  Either way, in order to fix this issue, you will need to add devices to your config.json (see the example in the repo, happy to help if needed).

**Comment by petrcassid** [comment]
kuestess: I'm running HOOBs core v3.3.1 Node v 14.14.1 The version of Insteonlocal I installed is 4.16 so I seem to be up to date. 

Here is what is in config.json currently. I've read through the insteinlocal setup documentation where I see the variables for devices, but I need an example of how it should look in config.json. If you can help me with that, I should be able to get to the InsteonUI or just keep adding devices manually. Appreciate your help.

  {
            "platform": "InsteonLocal",
            "plugin_map": {
                "plugin_name": "homebridge-platform-insteonlocal"
            }
        }

**Comment by petrcassid** [comment]
Also, there are no updates pending for any of my HOOBS plugins, including Insteonlocal.

**Comment by kuestess** [comment]
@petrcassid Clearly I need to test 0.4.16 more :-).  If you put:
```
"devices": [
				{ 
					"name": "Great Room Lamp",
					"deviceID" : "<Insteon ID>",
					"dimmable" : "yes",
					"deviceType" : "lightbulb" 
				}
 ],
```
below the platform line in your config above, that should make it happy enough to get you into the UI where you can add more devices.  Make sure to put your device ID in the above as well.

**Comment by petrcassid** [comment]
Here's what I have now. I had to make a couple of changes from your example to satisfy the json editor. File will save ok but service won't run. Is there a line out of place, or indent error?

     {
            "platform": "InsteonLocal",
            "plugin_map": {
                "plugin_name": "homebridge-platform-insteonlocal",
                "devices": [
                    {
                        "name": "Fam Rm Plugin",
                        "deviceID": "2EA02A",
                        "dimmable": "yes",
                        "deviceType": "dimmer"
                    }
                ]
            }
        }

**Comment by kuestess** [comment]
@petrcassid HOOBS seems to use some additional fields in their configs.  From what I can tell, I think you need to put the `devices` array outside of the plugin map.  You'll also need to add some additional information to actually connect to the hub.  Your config should look something like the below (indentation doesn't matter unless you like it to look fancy):

```
{
        "platform": "InsteonLocal",
        "plugin_map": {
            "plugin_name": "homebridge-platform-insteonlocal"
	},
		"name": "Insteon Local Platform",
		"user": "<username from Insteon app>",
		"pass": "<password from Insteon app>",
		"host": "<local IP of your Insteon hub>",
		"port": "<port from Insteon app [usually 25105]>",
		"model": "2245",
		"refresh":"0",
		"server_port": "3000",
		"keepAlive": "3600",
		"devices": [
			{
				"name": "Fam Rm Plugin",
				"deviceID": "2EA02A",
				"dimmable": "yes",
				"deviceType": "dimmer"
			}
		]
}
```

**Comment by petrcassid** [comment]
Success. That worked. I can also now access the InsteonUI. Many thanks for your help. 

FYI, The user and password are not the ones used to set up the app to the Insteon account. It is the one printed on label on the bottom of the Insteon hub. That's also where the hub port (25105) is listed.

**Comment by kuestess** [comment]
@petrcassid Glad you got it working!

**Comment by patrick131** [comment]
I hope someone can help me also.  I'm running on OSX and when I enable the homebridge-platform-insteonlocal my Homebridge fails to load. My logs show the below which means nothing to me.  Based on the above, my config looks good.  

[4/4/2022, 1:30:38 AM] [TplinkKasaSmarthome] Configuring cached accessory: [Natalie] UUID: f7b1c751-d22b-46a4-8980-7a1a3295d990 deviceId: 8012D5AF9EACCDEA1063EC37A978E1071EE9890E 
[4/4/2022, 1:30:38 AM] [Meross] Plugin initialised. Setting up accessories....
[4/4/2022, 1:30:38 AM] TypeError: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at new NodeError (node:internal/errors:372:5)
    at Hash.update (node:internal/crypto/hash:105:11)
    at Object.generate (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/uuid.ts:11:11)
    at InsteonLocalAccessory.init (/usr/local/lib/node_modules/homebridge-platform-insteonlocal/index.js:2546:21)
    at new InsteonLocalAccessory (/usr/local/lib/node_modules/homebridge-platform-insteonlocal/index.js:2503:12)
    at /usr/local/lib/node_modules/homebridge-platform-insteonlocal/index.js:837:19
    at Array.forEach (<anonymous>)
    at InsteonLocalPlatform.accessories (/usr/local/lib/node_modules/homebridge-platform-insteonlocal/index.js:836:15)
    at /usr/local/lib/node_modules/homebridge/src/bridgeService.ts:534:24
    at new Promise (<anonymous>)
[4/4/2022, 1:30:38 AM] Got SIGTERM, shutting down Homebridge...
[4/4/2022, 1:30:38 AM] [Hyatt House] Connected to Insteon Model 2245 Hub...
[4/4/2022, 1:30:38 AM] [Hyatt House] Insteon event listener started...
[4/4/2022, 1:30:38 AM] [Hyatt House] Started Insteon Express server...
[4/4/2022, 1:30:38 AM] [Meross] [attic fan] initialising with options {"connection":"hybrid","inUsePowerThreshold":0,"logging":"standard","showAs":"switch"}.
