### ISSUE TITLE
ERROR LOADING PLUGIN homebridge-platform-insteonlocal:

### ISSUE THREAD

**Issue by robk1979** [kuestess/homebridge-platform-insteonlocal#133]
[2/24/2021, 6:49:24 PM] ERROR LOADING PLUGIN homebridge-platform-insteonlocal:
[2/24/2021, 6:49:24 PM] Error: Cannot find module 'request'
Require stack:
- /usr/lib/node_modules/homebridge-platform-insteonlocal/index.js
- /usr/lib/node_modules/homebridge/lib/plugin.js
- /usr/lib/node_modules/homebridge/lib/pluginManager.js
- /usr/lib/node_modules/homebridge/lib/server.js
- /usr/lib/node_modules/homebridge/lib/cli.js
- /usr/lib/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-platform-insteonlocal/index.js:2:15)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)

Please help!

**Comment by kuestess** [comment]
@robk1979 Looks like the plugin is missing the `request` module.  Try reinstalling using `npm -g install homebridge-platform-insteonlocal`.  That should reinstall `request` as well, which is a dependency for the plugin.

**Comment by microbmen** [comment]
I tried. `npm install -g request `                                                                                                                                     

I get - 
npm WARN deprecated har-validator@5.1.5: this library is no longer supported                                                                                                   
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142                                                            
                                                                                                                                                                               
added 47 packages, and audited 48 packages in 3m                                                                                                                               
                                                                                                                                                                               
2 packages are looking for funding                                                                                                                                             
  run `npm fund` for details                                                                                                                                                   
                                                                                                                                                                               
found 0 vulnerabilities

**Comment by microbmen** [comment]
update, 
I hade to manually install `request, underscore, q, home-controller, moment, util, express`
`npm install -g underscore` , etc. for each of the packages above.

then it loaded.

however even though it loaded my Insteon devices do not respond.  I get the follow messages:

`[3/9/2021, 11:18:40 PM] [homebridge-platform-insteonlocal] This plugin generated a warning from the characteristic 'On': SET handler returned write response value, though the characteristic doesn't support write response. See https://git.io/JtMGR for more info.  `

**Comment by kuestess** [comment]
@microbmen You can ignore the warnings about deprecated packages.  It should still install them and work correctly.  Your solution of manually installing some of the dependencies is interesting - I had this same problem on another project (not this plugin).  I wonder if this is an issue with `npm`.  The characteristic warning above is from the new version of homebridge.  I haven't had time to look into it, but the plugin should still run fine.

**Comment by desmondfuller** [comment]
I had to do an install of the home-controller module in the lastest plugin.

sudo npm -g install home-controller
