### ISSUE TITLE
Warning from the characteristic 'On': SET handler

### ISSUE THREAD

**Issue by desmondfuller** [kuestess/homebridge-platform-insteonlocal#136]
Receiving these errors. Guessing this is X10 related since this is what I'm seeing errors on.

[28/02/2021, 15:59:15] [Insteon Local Platform] Setting power state of Juliet Landing to on
**[28/02/2021, 15:59:15] [homebridge-platform-insteonlocal] This plugin generated a warning from the characteristic 'On': SET handler returned write response value, though the characteristic doesn't support write response. See https://git.io/JtMGR for more info.**
[28/02/2021, 15:59:15] [Insteon Local Platform] Connected to Insteon Model 2242 Hub...
[28/02/2021, 15:59:16] [Insteon Local Platform] Setting power state of Juliet Landing to on
**[28/02/2021, 15:59:16] [homebridge-platform-insteonlocal] This plugin generated a warning from the characteristic 'On': SET handler returned write response value, though the characteristic doesn't support write response. See https://git.io/JtMGR for more info.**
[28/02/2021, 15:59:16] [Insteon Local Platform] Setting power state of Juliet Landing to on
[28/02/2021, 15:59:16] [homebridge-platform-insteonlocal] This plugin generated a warning from the characteristic 'On': SET handler returned write response value, though the characteristic doesn't support write response. See https://git.io/JtMGR for more info.

**Comment by ekristen** [comment]
I'm seeing this issue as well..

```
Error: 
    at On.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2164:105)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1645:22
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18
    at /homebridge/node_modules/homebridge-platform-insteonlocal/index.js:1480:6
    at _fulfilled (/homebridge/node_modules/homebridge-platform-insteonlocal/node_modules/q/q.js:854:54)
    at /homebridge/node_modules/homebridge-platform-insteonlocal/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/homebridge/node_modules/homebridge-platform-insteonlocal/node_modules/q/q.js:816:13)
    at /homebridge/node_modules/homebridge-platform-insteonlocal/node_modules/q/q.js:624:44
    at runSingle (/homebridge/node_modules/homebridge-platform-insteonlocal/node_modules/q/q.js:137:13)
    at flush (/homebridge/node_modules/homebridge-platform-insteonlocal/node_modules/q/q.js:125:13)
```

**Comment by kuestess** [comment]
@ekristen Does this completely crash the plugin or homebridge?

**Comment by ekristen** [comment]
Doesn’t appear to, just throws the error on every device that’s has on

**Comment by ekristen** [comment]
Seems to be happening on all device types.

```
[3/16/2021, 11:49:55 AM] [homebridge-platform-insteonlocal] This plugin generated a warning from the characteristic 'Rotation Speed': SET handler returned write response value, though the characteristic doesn't support write response. See https://git.io/JtMGR for more info.
[3/16/2021, 11:49:55 AM] [homebridge-platform-insteonlocal] This plugin generated a warning from the characteristic 'Rotation Speed': SET handler returned write response value, though the characteristic doesn't support write response. See https://git.io/JtMGR for more info.
[3/16/2021, 11:49:56 AM] [homebridge-platform-insteonlocal] This plugin generated a warning from the characteristic 'Rotation Speed': SET handler returned write response value, though the characteristic doesn't support write response. See https://git.io/JtMGR for more info.
```

**Comment by kuestess** [comment]
Appears that the new version of homebridge is picky about the return type from the set handler.  Shouldn't affect functionality, but will fix this in an upcoming release.

**Comment by matttttttttttttt** [comment]
I've seen something very similar to the posts above:

[5/3/2021, 8:24:26 PM] [Insteon Local Platform] Discard on, sent too close to dim
[5/3/2021, 8:24:26 PM] [Insteon Local Platform] Fireplace is on at 100%
[5/3/2021, 8:24:26 PM] [Insteon Local Platform] Setting level of Kitchen to 100%
[5/3/2021, 8:24:27 PM] [Insteon Local Platform] Discard on, already at commanded state
[5/3/2021, 8:24:28 PM] [homebridge-platform-insteonlocal] Characteristic 'Brightness': SET handler returned write response value, though the characteristic doesn't support write response. See https://git.io/JtMGR for more info.
[5/3/2021, 8:24:28 PM] [homebridge-platform-insteonlocal] Error: 
    at Brightness.Characteristic.characteristicWarning (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2038:105)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1663:22
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18
    at InsteonLocalAccessory.setBrightnessLevel (/usr/lib/node_modules/homebridge-platform-insteonlocal/index.js:1164:2)
    at Brightness.emit (events.js:315:20)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1632:16
    at new Promise (<anonymous>)
    at Brightness.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1630:14)
    at step (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
[5/3/2021, 8:24:28 PM] [Insteon Local Platform] Discard on, sent too close to dim

**Comment by NorthernMan54** [comment]
@kuestess Any ETA for a quick fix for this issue ?  If you remove the value ie 'change callback(null, self.currentState) to callback(null)' from the set callbacks it will resolve the issue.  Just needs to be completed for each set function

https://github.com/kuestess/homebridge-platform-insteonlocal/blob/cbf40ed2d380114f3a2d77b75bd6eb3bc5c3a4b6/index.js#L901

**Comment by kuestess** [comment]
@NorthernMan54 Figure it had something to do with the callbacks, but hadn't had a chance to dig into it.  You've done the hard part, so let me see if I can get a fix out in the next day or so.

**Comment by NorthernMan54** [comment]
I had to fix a couple of mine as well, so I had a little bit of experience

**Comment by kuestess** [comment]
@NorthernMan54 Fixed version up on nom.  Thanks again for your help!

**Comment by NorthernMan54** [comment]
Tks very much
