### ISSUE TITLE
'Hub' link

### ISSUE THREAD

**Issue by Calorion** [kuestess/homebridge-platform-insteonlocal#142]
I'm having difficulty getting started. The documentation says 
>Direct your browser to the host that you have Insteonlocal running on and the port configured in your config.json (ie, 127.0.0.1:3000 if running on the local machine). Click on the 'Hub' link.

But I see no 'Hub' link in Homebridge Config. Where do I find this?

**Comment by kuestess** [comment]
@Calorion The plugin has its own UI, so if you see the Homebridge UI, you're not at the right place :-).  Just put the IP of the homebridge machine in your browser, followed by the port that is in your config.json (`server_port`).  That should open  up the plugin ui.  If not, you may need to change the port in your config.json.

**Comment by Calorion** [comment]
I tried using the port under 
`"bridge": {
"port":`

but that just gets me the error: `{"status":-70409}`.

**Comment by kuestess** [comment]
@Calorion You need to use the `server-port` under the `platform: Insteonlocal` section (see the example config.json).  If its not in your config, it defaults to 3000.  You'll need to add it to your config if you want a different port than that.

**Comment by BobHackett2** [comment]
I'm having trouble getting started too.  Then I type in the IP of the homebridge server followed by the server_port, i get nothing.  No UI comes up at all, it just gives me a server connection error.

**Comment by kuestess** [comment]
@BobHackett2 Can you post your config to troubleshoot?

**Comment by BobHackett2** [comment]
"platform": "InsteonLocal",
    "name": "InsteonLocal",
    "user": "admin",
    "pass": "........",
    "host": "192.168.2.8",
    "port": "25105",
    "model": "2245",
    "server_port": 3000

**Comment by kuestess** [comment]
@BobHackett2 That appears correct - just to confirm, you're using the IP of the machine running homebridge and you've exposed the port if running in a docker container.  Do you get the message 'Initializing Insteon UI ' in the log?

**Comment by BobHackett2** [comment]
Yes.  The IP address of the Mac mini I'm using is 192.168.2.3, so I enter http://192.168.2.3:3000 in the address bar and I end up with "Safari Can't Connect to the Server".

Yes, I see this in the log:
[8/18/2021, 6:22:57 PM] [InsteonLocal] Initializing InsteonLocal platform...
Initializing Insteon UI

**Comment by BobHackett2** [comment]
@kuestess Do you have any ideas?  Thanks!

**Comment by kuestess** [comment]
@BobHackett2 My setup is very similar, running on a Mac and nearly identical config and everything works fine.  Do you get the message 'Started Insteon Express server...' in your log?

**Comment by BobHackett2** [comment]
@kuestess Just looked at the log.  I don't see 'Started Insteon Express server...' in there.  Did I miss a step somewhere during setup?  Thanks!

**Comment by kuestess** [comment]
@BobHackett2 Nope, you didn't miss anything but perhaps something is wonky with the code.  Try adding `"use_express": true` to your config and see if that works.

**Comment by BobHackett2** [comment]
@kuestess No luck

**Comment by BobHackett2** [comment]
@kuestess I have a hub pro that I set up Homebridge on as well to see if I'd have any better luck there, but I get the same result.  No connection to InsteonUI.  :(

**Comment by kuestess** [comment]
@BobHackett2 Can you run `lsof -i :3000` and post the output.  Please also run homebridge in debug mode `homebridge -D` and post that output.

**Comment by BobHackett2** [comment]
@kuestess I'm not sure if I'm doing `lsof -i :3000` right.  I get no output.  Here is the output from `homebridge -D`:

Toms-Mac-mini:~ Gabriele$ homebridge -D
Initializing HAP-NodeJS v0.9.4...
[8/21/2021, 4:24:19 PM] Loaded config.json with 2 accessories and 3 platforms.
[8/21/2021, 4:24:19 PM] Loaded 1 cached accessories from cachedAccessories.
[8/21/2021, 4:24:19 PM] ---
[8/21/2021, 4:24:19 PM] Loaded plugin: homebridge-aladdin-connect-garage-door@1.0.5
[8/21/2021, 4:24:19 PM] Registering accessory 'homebridge-aladdin-connect-garage-door.AladdinConnectGarageDoorOpener'
[8/21/2021, 4:24:19 PM] ---
[8/21/2021, 4:24:19 PM] Loaded plugin: homebridge-config-ui-x@4.41.2
[8/21/2021, 4:24:19 PM] Registering platform 'homebridge-config-ui-x.config'
[8/21/2021, 4:24:19 PM] ---
[8/21/2021, 4:24:19 PM] Loaded plugin: homebridge-nest-cam@7.4.0
[8/21/2021, 4:24:19 PM] Registering platform 'homebridge-nest-cam.Nest-cam'
[8/21/2021, 4:24:19 PM] ---
[8/21/2021, 4:24:19 PM] Loaded plugin: homebridge-platform-insteonlocal@0.4.19
homebridge API version: 2.7
[8/21/2021, 4:24:19 PM] Registering platform 'homebridge-platform-insteonlocal.InsteonLocal'
[8/21/2021, 4:24:19 PM] ---
[8/21/2021, 4:24:19 PM] Loading 3 platforms...
[8/21/2021, 4:24:19 PM] [Config] Initializing config platform...
[8/21/2021, 4:24:19 PM] [Config] Spawning homebridge-config-ui-x with PID 54929
[8/21/2021, 4:24:19 PM] [InsteonLocal] Initializing InsteonLocal platform...
Initializing Insteon UI 
Reading config from /Users/Gabriele/.homebridge/config.json
Found 3 platform(s) in config
Creating new insteon.json
No devices in config
[8/21/2021, 4:24:19 PM] [InsteonLocal] No devices defined - please add devices to your config.json
[8/21/2021, 4:24:19 PM] [InsteonLocal] Found 0 devices in config
[8/21/2021, 4:24:19 PM] [Nest-cam] Initializing Nest-cam platform...
[8/21/2021, 4:24:19 PM] [Nest-cam] Using motionDetection from config: true
[8/21/2021, 4:24:19 PM] [Nest-cam] Using doorbellAlerts from config: true
[8/21/2021, 4:24:19 PM] [Nest-cam] Using doorbellSwitch from config: true
[8/21/2021, 4:24:19 PM] [Nest-cam] Using streamingSwitch from config: true
[8/21/2021, 4:24:19 PM] [Nest-cam] Using chimeSwitch from config: true
[8/21/2021, 4:24:19 PM] [Nest-cam] Using announcementsSwitch from config: true
[8/21/2021, 4:24:19 PM] [Nest-cam] Using audioSwitch from config: true
[8/21/2021, 4:24:19 PM] [Nest-cam] Defaulting structures to []
[8/21/2021, 4:24:19 PM] [Nest-cam] Defaulting cameras to []
[8/21/2021, 4:24:19 PM] Loading 2 accessories...
[8/21/2021, 4:24:19 PM] [Audi] Initializing AladdinConnectGarageDoorOpener accessory...
[8/21/2021, 4:24:19 PM] [Porsche] Initializing AladdinConnectGarageDoorOpener accessory...
[8/21/2021, 4:24:19 PM] [Nest-cam] Configuring accessory Front Door Nest Hello
[8/21/2021, 4:24:19 PM] [Nest-cam] Using importantOnly from config: true
[8/21/2021, 4:24:19 PM] [Nest-cam] Creating microphone for Front Door Nest Hello.
[8/21/2021, 4:24:19 PM] [Nest-cam] Creating doorbell sensor for Front Door Nest Hello.
[8/21/2021, 4:24:19 PM] [Nest-cam] Creating doorbell switch for Front Door Nest Hello.
[8/21/2021, 4:24:19 PM] [Nest-cam] Creating switch for Front Door Nest Hello Streaming.
[8/21/2021, 4:24:19 PM] [Nest-cam] Creating switch for Front Door Nest Hello Chime.
[8/21/2021, 4:24:19 PM] [Nest-cam] Creating switch for Front Door Nest Hello Announcements.
[8/21/2021, 4:24:19 PM] [Nest-cam] Creating switch for Front Door Nest Hello Audio.
[8/21/2021, 4:24:19 PM] [Nest-cam] Authenticating via Google refresh token.
Preparing Advertiser for 'Tom's Mac mini Homebridge 6281' using ciao backend!
Setup Payload:
X-HM://00248JG6N8T3E
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
Or enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 463-70-991 │     
    └────────────┘     
                       
[8/21/2021, 4:24:19 PM] Error: listen EADDRINUSE: address already in use :::51172
    at Server.setupListenHandle [as _listen2] (net.js:1320:16)
    at listenInCluster (net.js:1368:12)
    at Server.listen (net.js:1454:7)
    at EventedHTTPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:155:20)
    at HAPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:316:21)
    at Bridge.Accessory.publish (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1231:18)
    at BridgeService.publishBridge (/usr/local/lib/node_modules/homebridge/src/bridgeService.ts:213:17)
    at Server.publishBridge (/usr/local/lib/node_modules/homebridge/src/server.ts:186:24)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:177:24
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:176:5)
[8/21/2021, 4:24:19 PM] Got SIGTERM, shutting down Homebridge...
[8/21/2021, 4:24:20 PM] [Homebridge UI] Homebridge Config UI X v4.41.2 is listening on :: port 8581
[8/21/2021, 4:24:20 PM] [Homebridge UI] Error: listen EADDRINUSE: address already in use :::8581
[8/21/2021, 4:24:20 PM] [Homebridge UI] Another process or service on this host is using port 8581.
[8/21/2021, 4:24:20 PM] [Homebridge UI] Please stop the other service or change the port you have assigned to homebridge-config-ui-x.
[8/21/2021, 4:24:20 PM] [Homebridge UI] Ending process now.
[8/21/2021, 4:24:21 PM] [Nest-cam] Found zone Zone 2 for Front Door (Nest Hello)
[8/21/2021, 4:24:21 PM] [Nest-cam] Found zone Zone 1 for Front Door (Nest Hello)
[8/21/2021, 4:24:21 PM] [Nest-cam] Front Door (Nest Hello) has stranger_detection
[8/21/2021, 4:24:21 PM] [Nest-cam] Found face Dad for b66c9dc1-2667-11ea-b100-0eb7db574612
[8/21/2021, 4:24:21 PM] [Nest-cam] Found face Johnny Piatek for b66c9dc1-2667-11ea-b100-0eb7db574612
[8/21/2021, 4:24:21 PM] [Nest-cam] Found face Mail Lady for b66c9dc1-2667-11ea-b100-0eb7db574612
[8/21/2021, 4:24:21 PM] [Nest-cam] Found face The Maids for b66c9dc1-2667-11ea-b100-0eb7db574612
[8/21/2021, 4:24:21 PM] [Nest-cam] Found face The Maids for b66c9dc1-2667-11ea-b100-0eb7db574612
[8/21/2021, 4:24:21 PM] [Nest-cam] Found face The Maids for b66c9dc1-2667-11ea-b100-0eb7db574612
[8/21/2021, 4:24:21 PM] [Nest-cam] Found face Tom for b66c9dc1-2667-11ea-b100-0eb7db574612
[8/21/2021, 4:24:21 PM] [Nest-cam] Creating motion sensor for Front Door Nest Hello Motion.
[8/21/2021, 4:24:21 PM] [Nest-cam] Creating motion sensor for Front Door Nest Hello Sound.
[8/21/2021, 4:24:21 PM] [Nest-cam] Creating motion sensor for Front Door Nest Hello Person.
[8/21/2021, 4:24:21 PM] [Nest-cam] Creating motion sensor for Front Door Nest Hello Package Delivered.
[8/21/2021, 4:24:21 PM] [Nest-cam] Creating motion sensor for Front Door Nest Hello Package Retrieved.
[8/21/2021, 4:24:21 PM] [Nest-cam] Creating motion sensor for Front Door Nest Hello Zone - Zone 2.
[8/21/2021, 4:24:21 PM] [Nest-cam] Creating motion sensor for Front Door Nest Hello Zone - Zone 1.
[8/21/2021, 4:24:21 PM] [Nest-cam] Creating motion sensor for Front Door Nest Hello Face - Dad.
[8/21/2021, 4:24:21 PM] [Nest-cam] Creating motion sensor for Front Door Nest Hello Face - Unknown.
[8/21/2021, 4:24:21 PM] [Nest-cam] Creating motion sensor for Front Door Nest Hello Face - Johnny Piatek.
[8/21/2021, 4:24:21 PM] [Nest-cam] Creating motion sensor for Front Door Nest Hello Face - Unknown.
[8/21/2021, 4:24:21 PM] [Nest-cam] Creating motion sensor for Front Door Nest Hello Face - Mail Lady.
[8/21/2021, 4:24:21 PM] [Nest-cam] Creating motion sensor for Front Door Nest Hello Face - Unknown.
[8/21/2021, 4:24:21 PM] [Nest-cam] Creating motion sensor for Front Door Nest Hello Face - The Maids.
[8/21/2021, 4:24:21 PM] [Nest-cam] Creating motion sensor for Front Door Nest Hello Face - Unknown.
[8/21/2021, 4:24:21 PM] [Nest-cam] Creating motion sensor for Front Door Nest Hello Face - The Maids.
[8/21/2021, 4:24:21 PM] [Nest-cam] Creating motion sensor for Front Door Nest Hello Face - Unknown.
[8/21/2021, 4:24:21 PM] [Nest-cam] Creating motion sensor for Front Door Nest Hello Face - The Maids.
[8/21/2021, 4:24:21 PM] [Nest-cam] Creating motion sensor for Front Door Nest Hello Face - Unknown.
[8/21/2021, 4:24:21 PM] [Nest-cam] Creating motion sensor for Front Door Nest Hello Face - Tom.
[8/21/2021, 4:24:21 PM] [Nest-cam] Creating motion sensor for Front Door Nest Hello Face - Unknown.
[8/21/2021, 4:24:21 PM] [Nest-cam] Creating motion sensor for Front Door Nest Hello Face - Unknown.
[8/21/2021, 4:24:21 PM] [Nest-cam] Creating motion sensor for Front Door Nest Hello Face - Unknown.
[8/21/2021, 4:24:21 PM] [Nest-cam] Creating motion sensor for Front Door Nest Hello Face - Unknown.
[8/21/2021, 4:24:21 PM] [Nest-cam] Creating motion sensor for Front Door Nest Hello Face - Unknown.
[8/21/2021, 4:24:21 PM] [Nest-cam] Creating motion sensor for Front Door Nest Hello Face - Unknown.
[8/21/2021, 4:24:21 PM] [Nest-cam] Creating motion sensor for Front Door Nest Hello Face - Unknown.
[8/21/2021, 4:24:21 PM] [Nest-cam] Creating motion sensor for Front Door Nest Hello Face - Unknown.
[8/21/2021, 4:24:21 PM] [Nest-cam] Creating motion sensor for Front Door Nest Hello Face - Unknown.
[8/21/2021, 4:24:21 PM] [Nest-cam] Creating motion sensor for Front Door Nest Hello Face - Unknown.
[8/21/2021, 4:24:21 PM] [Nest-cam] Creating motion sensor for Front Door Nest Hello Face - Unknown.
[8/21/2021, 4:24:21 PM] [Nest-cam] Creating motion sensor for Front Door Nest Hello Face - Unknown.
[8/21/2021, 4:24:21 PM] [Nest-cam] Creating motion sensor for Front Door Nest Hello Face - Unknown.
[8/21/2021, 4:24:21 PM] [Nest-cam] Creating motion sensor for Front Door Nest Hello Face - Unknown.

**Comment by kuestess** [comment]
@BobHackett2 If you got no output from `lsof` that means nothing is listening on that port, which tells me that the express server isn't starting for some reason.  I noticed the message `No devices defined - please add devices to your config.json`.  Have you defined any Insteon devices in your `config.json`?  If not, that may prevent the plugin from loading the express server.

**Comment by BobHackett2** [comment]
@kuestess No, I thought that the InsteonUI would allow me to pull them in automatically from my hub.  Did I misunderstand something?  I will try adding some devices manually and see if that makes a difference.

**Comment by kuestess** [comment]
@BobHackett2 It will, although to be honest the Homebridge ui gui is probably better :-).  I'll be incorporating a PR soon that should make it easier.  Try manually adding a device and that should get you going.

**Comment by BobHackett2** [comment]
@kuestess That was it!  I manually added a device and that finally prompted the Insteon Express Server to start!  Thanks for all your help!

**Comment by kuestess** [comment]
@BobHackett2 Awesome - glad that worked.  I realize it’s a bit of chicken and egg with the config, but I’ll see if I can figure out how to get the config to load even without devices configured.

**Comment by Calorion** [comment]
I'm having the exact same problem: HOOBS.local:3000 times out, lsof -i :3000 outputs nothing, and I'm getting the same error on startup. 

When I install, I'm getting these errors. Could these be the issue?
![image](https://user-images.githubusercontent.com/3050950/130373680-9c8d0af2-8855-40ab-b60d-7335232df6bb.png)

**Comment by kuestess** [comment]
@Calorion If you don't have devices defined in your config, then this is likely the issue.  I just pushed a fix that should take care of this an make config via the homebridge UI easier.

**Comment by Calorion** [comment]
Unfortunately, nothing has changed with the update. I deleted the HOOBS bridge and started over, but the connection to `hoobs.local:3000` times out every time. In the log it says

`8/22/2021, 9:17:17 PMInsteon BridgeInsteonLocalERRORNo devices defined - please add devices to your config.json`
`8/22/2021, 9:17:17 PMInsteon BridgeWARNINGunhandled rejection: TypeError: "path" is not defined: undefined`
