### ISSUE TITLE
Error Getting Hub Info

### ISSUE THREAD

**Issue by ixiom** [kuestess/homebridge-platform-insteonlocal#145]
It's strange, this was working in a previous version. However, now when I try to get the hub info, Homebridge crashes with the following error:

`Getting Hub info
undefined
[6/13/2021, 1:46:01 AM] TypeError: Cannot read property 'id' of undefined
    at /homebridge/node_modules/homebridge-platform-insteonlocal/insteon-ui.js:1588:20
    at /homebridge/node_modules/homebridge-platform-insteonlocal/node_modules/q/q.js:2055:17
    at runSingle (/homebridge/node_modules/homebridge-platform-insteonlocal/node_modules/q/q.js:137:13)
    at flush (/homebridge/node_modules/homebridge-platform-insteonlocal/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)`

**Comment by kuestess** [comment]
@ixiom Looks like your hub is not responding - are you able to control devices in the Home app?  The 'undefined' on the second line of your log is supposed to be the hub info that was returned from the request to the hub.  Since nothing was returned, it can't get the `id` property, which is the rest of the error above.

**Comment by ixiom** [comment]
Yes, I can control other devices with the Home app. I can also control the Insteon switches with the Insteon app, so it's quite strange.

**Comment by mikeypdev** [comment]
I had the same issue, and was able to fix it by reinstalling the q module from npm.
`npm -g install q`
(note that I'm on a regular Raspian install, so I had to sudo the above command)
