### ISSUE TITLE
Plugin TypeError: "path" is not defined: undefined

### ISSUE THREAD

**Issue by tsawyer** [kuestess/homebridge-platform-insteonlocal#156]
This is a new Homebridge install using the Pi GUI image. I have been able to add other Plugins that have settings but the json setup is giving me problems. Here's error from the log:

[04/09/2021, 08:56:15] [InsteonLocal] No devices defined - please add devices to your config.json
[04/09/2021, 08:56:15] TypeError: "path" is not defined: undefined
    at new SerialPort (/usr/local/lib/node_modules/homebridge-platform-insteonlocal/node_modules/@serialport/stream/lib/index.js:116:11)
    at Insteon.serial (/usr/local/lib/node_modules/homebridge-platform-insteonlocal/node_modules/home-controller/lib/Insteon/index.js:153:17)
    at InsteonLocalPlatform.connectToHub (/usr/local/lib/node_modules/homebridge-platform-insteonlocal/index.js:415:7)
    at new InsteonLocalPlatform (/usr/local/lib/node_modules/homebridge-platform-insteonlocal/index.js:312:8)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:440:40
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:372:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:159:29)

And here's my json:
{
    "bridge": {
        "name": "Homebridge 9471",
        "username": "DC:A6:32:95:DA:7B",
        "pin": "733-58-663"
    },
    "platforms": [
        {
            "platform": "InsteonLocal",
            "name": "Insteon Local Platform",
            "user": "Ellyn272",
            "pass": "<from back of Hub v2>",
            "host": "192.168.1.165",
            "port": "25105",
            "model": "2245",
            "refresh": "0",
            "server_port": "3000",
            "keepAlive": "3600",
            "devices": [
                {
                    "name": "Test Outlet",
                    "deviceID": "54FD5C",
                    "dimmable": "no",
                    "deviceType": "outlet"
                }
            ]
        }
    ],
    "accessories": [],
    "platform": "InsteonLocal"
}

I am able to browse to the Hub v2 with userid and password from the back of the hub.

**Comment by kuestess** [comment]
@tsawyer For some reason it looks like the plugin is trying to open a serial connection which doesn't exist.  I think this is because you have an extra platform line in your config.  Try deleting the `"platform": "InsteonLocal"` line right after 'accessories' in the config above.

**Comment by tsawyer** [comment]
OK, I sorted this out by looking at the overall config (selecting Config from the menu at the top of the UI). The example config here on GitHub is an example of the overall config. Adding json to the Plugin puts it in the overall config. 

Here is what I added to the Plugin's json:
```
{
    "platform": "InsteonLocal",
    "name": "Insteon Local Platform",
    "user": "<userid>",
    "pass": "<passwd>",
    "host": "192.168.1.165",
    "port": "25105",
    "model": "2245",
    "refresh": "0",
    "server_port": "3000",
    "keepAlive": "3600",
    "devices": [
        {
            "name": "Test Outlet",
            "deviceID": "54FD5C",
            "dimmable": "no",
            "deviceType": "outlet"
        }
    ]
} 
```
The Test Outlet is now working from Homekit. :-)

**Comment by kuestess** [comment]
Great, glad you got it working!
