### ISSUE TITLE
0.3.5 Error

### ISSUE THREAD

**Issue by awaspaas** [kuestess/homebridge-platform-insteonlocal#16]
I am getting this error after installing 0.3.5. Rolling back to 0.3.4 works fine.

[2018-7-25 10:54:52] [Insteon Local Platform] Initializing InsteonLocal platform...
/usr/local/lib/node_modules/homebridge-platform-insteonlocal/index.js:240
			hub.httpClient(config, function(had_error) {
			               ^

ReferenceError: config is not defined
    at InsteonLocalPlatform.connectToHub (/usr/local/lib/node_modules/homebridge-platform-insteonlocal/index.js:240:19)
    at new InsteonLocalPlatform (/usr/local/lib/node_modules/homebridge-platform-insteonlocal/index.js:196:11)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:325:32)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:85:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:43:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)

**Comment by kuestess** [comment]
@awaspaas I see my stupid error.  Will get this fixed later today.

**Comment by kuestess** [comment]
@awaspaas Uploaded a fix for the connection error.  Made sure that I tested a little better this time :-)

**Comment by awaspaas** [comment]
It works. Thank you!
