### ISSUE TITLE
Error when selecting device on web server

### ISSUE THREAD

**Issue by dxdr** [kuestess/homebridge-platform-insteonlocal#169]
When I try and select a device on the web server, I get the following error...

TypeError: Cannot read properties of undefined (reading 'filter')
    at /usr/local/lib/node_modules/homebridge-platform-insteonlocal/insteon-ui.js:1176:70
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/homebridge-platform-insteonlocal/insteon-ui.js:1152:21
    at Array.forEach (<anonymous>)
    at buildDeviceSceneTable (/usr/local/lib/node_modules/homebridge-platform-insteonlocal/insteon-ui.js:1112:45)
    at /usr/local/lib/node_modules/homebridge-platform-insteonlocal/insteon-ui.js:564:14
    at buildDeviceSceneData (/usr/local/lib/node_modules/homebridge-platform-insteonlocal/insteon-ui.js:1058:3)
    at InsteonUI.renderDevicePage (/usr/local/lib/node_modules/homebridge-platform-insteonlocal/insteon-ui.js:561:4)
    at InsteonUI.handleRequest (/usr/local/lib/node_modules/homebridge-platform-insteonlocal/insteon-ui.js:1954:9)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/homebridge-platform-insteonlocal/node_modules/express/lib/router/layer.js:95:5)

This happens on about half of the 20 or so devices I have.  Any suggestions?

**Comment by kuestess** [comment]
@dxdr Try using 'Get All Dev Links' and see if that fixes it.

**Comment by dxdr** [comment]
Just tried, still getting the same error messages

**Comment by kuestess** [comment]
@dxdr Looking into this more (sorry for the delay), I'm wondering if there's something screwy in your `insteon.json`.  For quick and dirty troubleshooting, can you rename your `insteon.json` (its in the homebridge directory), restart homebridge, and then get hub info and devices again.  This may help eliminate a potential cause for the error.
