### ISSUE TITLE
Get devices on a working setup cause a crash and requires server restart

### ISSUE THREAD

**Issue by sahafeez** [kuestess/homebridge-platform-insteonlocal#172]
Click get devices on the 127.0.0.1:3000 interface

 No changes to the devices. I just replaced a few batteries in the door sensors. 

The interface on 127.0.0.1:3000 is gone at this point and I have to restart the server - the full server, not just Homebridge.

On restart there are no devices in the list and I have to click on get devices.

`[11/22/2021, 3:21:08 PM] [homebridge-lacrosseview] Discovering devices
Getting devices from Hub
Saved new insteon config
Created backup of previous config
Done writing Insteon config
Reading devices from insteon.json
Building Hub scene data...
Getting Hub info
undefined

/usr/lib/node_modules/homebridge-platform-insteonlocal/node_modules/q/q.js:137
            task();
            ^
TypeError: Cannot read properties of undefined (reading 'id')
    at /usr/lib/node_modules/homebridge-platform-insteonlocal/insteon-ui.js:1588:20
    at /usr/lib/node_modules/homebridge-platform-insteonlocal/node_modules/q/q.js:2055:17
    at runSingle (/usr/lib/node_modules/homebridge-platform-insteonlocal/node_modules/q/q.js:137:13)
    at flush (/usr/lib/node_modules/homebridge-platform-insteonlocal/node_modules/q/q.js:125:13)
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
[11/22/2021, 3:28:22 PM] [Insteon] Child bridge process ended
[11/22/2021, 3:28:22 PM] [Insteon] Process Ended. Code: 1, Signal: null
[11/22/2021, 3:28:29 PM] [Insteon] Restarting Process...
[11/22/2021, 3:28:30 PM] [Insteon] Launched child bridge with PID 3143
homebridge API version: 2.7
[11/22/2021, 3:28:30 PM] Registering platform 'homebridge-platform-insteonlocal.InsteonLocal'`

**Comment by sahafeez** [comment]
All I did was click get hub info. The accessories screen reflected the current state of thing at the time so the system was connected to the hub.

Getting Hub info
[1/27/2022, 10:00:36 AM] [unifi-poe-control] Refreshing devices...
undefined

/usr/lib/node_modules/homebridge-platform-insteonlocal/node_modules/q/q.js:137
            task();
            ^
TypeError: Cannot read properties of undefined (reading 'id')
    at /usr/lib/node_modules/homebridge-platform-insteonlocal/insteon-ui.js:1588:20
    at /usr/lib/node_modules/homebridge-platform-insteonlocal/node_modules/q/q.js:2055:17
    at runSingle (/usr/lib/node_modules/homebridge-platform-insteonlocal/node_modules/q/q.js:137:13)
    at flush (/usr/lib/node_modules/homebridge-platform-insteonlocal/node_modules/q/q.js:125:13)
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
[1/27/2022, 10:00:44 AM] [InsteonLocal] Child bridge process ended

**Comment by kuestess** [comment]
@sahafeez You're clicking wrong? :-). It still seems like there's a connection issue with the hub or something else weird going on that has similar symptoms.  Your hub isn't returning any info from the request so when the code tries to do something with the `id` property....it pukes.  Are you getting the 'Connected to Insteon hub' message in your log (I think so from other issues).

**Comment by sahafeez** [comment]
Closing this. I am giving up on Insteon. They have stopped supporting stuff and EOL stuff that people still need. I bought the USB stick and it works just fine in place of the hub, but the idea doing the ton of work of moving everything work when are planing to move in the summer seems wasteful. Thank for everything!
