### ISSUE TITLE
Error after installing "TypeError: Cannot read property 'forEach' of undefined"

### ISSUE THREAD

**Issue by gregmichael** [kuestess/homebridge-platform-insteonlocal#195]
After plugin install via Homebridge on a raspberry pi, I am receiving upon visiting host for Insteonlocal:

TypeError: Cannot read property 'forEach' of undefined
    at buildDeviceTable (/usr/lib/node_modules/homebridge-platform-insteonlocal/insteon-ui.js:239:16)
    at InsteonUI.renderMainPage (/usr/lib/node_modules/homebridge-platform-insteonlocal/insteon-ui.js:185:2)
    at InsteonUI.handleRequest (/usr/lib/node_modules/homebridge-platform-insteonlocal/insteon-ui.js:1531:8)
    at Layer.handle [as handle_request] (/usr/lib/node_modules/homebridge-platform-insteonlocal/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/lib/node_modules/homebridge-platform-insteonlocal/node_modules/express/lib/router/index.js:323:13)
    at /usr/lib/node_modules/homebridge-platform-insteonlocal/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/lib/node_modules/homebridge-platform-insteonlocal/node_modules/express/lib/router/index.js:341:12)
    at next (/usr/lib/node_modules/homebridge-platform-insteonlocal/node_modules/express/lib/router/index.js:275:10)
    at expressInit (/usr/lib/node_modules/homebridge-platform-insteonlocal/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/usr/lib/node_modules/homebridge-platform-insteonlocal/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/lib/node_modules/homebridge-platform-insteonlocal/node_modules/express/lib/router/index.js:323:13)
    at /usr/lib/node_modules/homebridge-platform-insteonlocal/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/lib/node_modules/homebridge-platform-insteonlocal/node_modules/express/lib/router/index.js:341:12)
    at next (/usr/lib/node_modules/homebridge-platform-insteonlocal/node_modules/express/lib/router/index.js:275:10)
    at query (/usr/lib/node_modules/homebridge-platform-insteonlocal/node_modules/express/lib/middleware/query.js:45:5)
    at Layer.handle [as handle_request] (/usr/lib/node_modules/homebridge-platform-insteonlocal/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/lib/node_modules/homebridge-platform-insteonlocal/node_modules/express/lib/router/index.js:323:13)
    at /usr/lib/node_modules/homebridge-platform-insteonlocal/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/lib/node_modules/homebridge-platform-insteonlocal/node_modules/express/lib/router/index.js:341:12)
    at next (/usr/lib/node_modules/homebridge-platform-insteonlocal/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/usr/lib/node_modules/homebridge-platform-insteonlocal/node_modules/express/lib/router/index.js:174:3)
    at Function.handle (/usr/lib/node_modules/homebridge-platform-insteonlocal/node_modules/express/lib/application.js:174:10)

my config is:

        {
            "name": "Insteon Local Platform",
            "user": "NAME",
            "pass": "PW",
            "host": "10.0.0.2",
            "port": "25105",
            "model": "2245",
            "refresh": "false",
            "server_port": "8228",
            "keepAlive": "true",
            "platform": "InsteonLocal"
        }

I can't seem to figure it out, tried looking through previous tickets and can't find anything...

**Comment by kuestess** [comment]
@gregmichael You'll need to add the `devices` section to your config, similar to the example config here: [https://github.com/kuestess/homebridge-platform-insteonlocal/blob/master/config-example.json](https://github.com/kuestess/homebridge-platform-insteonlocal/blob/master/config-example.json). That should keep it from the restart cycle.

**Comment by kuestess** [comment]
@gregmichael This is fixed in 0.4.24.
