### ISSUE TITLE
Error: serial is Unsupported on this platform

### ISSUE THREAD

**Issue by i-did-that** [kuestess/homebridge-platform-insteonlocal#197]
I'm Running on a MacMini M1 that had the OS brought over from a MacMini X86.

The Hoobs log shows. 
Platform Insteonlocal Bridge Warning unhandled rejection: Error: serial is Unsupported on this platform

This looks to be an error reported by serialport. I deleted the serialport directories and reinstalled with 
npm -g install serialport@latest

After install the version is serialport@10.0.40

I still get the same error. I'm wondering if npm is somehow installing the X86 version or serialport, not the M1 version since this was an OS upgrade from a x86 Mini.

Any ideas?

**Comment by kuestess** [comment]
@i-did-that Yes, `serialport` has always been a bit of a pain.  I just installed on my M1, so it looks like there's an arm64 package.  You may need to copy the globally installed copy of `serialport` under the `home bridge-platform-insteonlocal/node_modules` directory.  Not sure why it won't find a global installation, but this usually fixes it.

**Comment by i-did-that** [comment]
@Kuestess Thanks, I tried that and it didn't change anything.  From a reddit user suggestion I added "model": "2245" after the port line in the configuration and now the bridge runs.  But it has a new set of errors. 

TypeError: Cannot read properties of undefined (reading 'forEach')
    at buildDeviceTable (/private/var/lib/hoobs/platforminsteonlocalbridge/node_modules/homebridge-platform-insteonlocal/insteon-ui.js:239:16)
    at InsteonUI.renderMainPage (/private/var/lib/hoobs/platforminsteonlocalbridge/node_modules/homebridge-platform-insteonlocal/insteon-ui.js:185:2)
    at InsteonUI.handleRequest (/private/var/lib/hoobs/platforminsteonlocalbridge/node_modules/homebridge-platform-insteonlocal/insteon-ui.js:1531:8)
    at Layer.handle [as handle_request] (/private/var/lib/hoobs/platforminsteonlocalbridge/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/private/var/lib/hoobs/platforminsteonlocalbridge/node_modules/express/lib/router/index.js:323:13)
    at /private/var/lib/hoobs/platforminsteonlocalbridge/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/private/var/lib/hoobs/platforminsteonlocalbridge/node_modules/express/lib/router/index.js:341:12)
    at next (/private/var/lib/hoobs/platforminsteonlocalbridge/node_modules/express/lib/router/index.js:275:10)
    at expressInit (/private/var/lib/hoobs/platforminsteonlocalbridge/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/private/var/lib/hoobs/platforminsteonlocalbridge/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/private/var/lib/hoobs/platforminsteonlocalbridge/node_modules/express/lib/router/index.js:323:13)
    at /private/var/lib/hoobs/platforminsteonlocalbridge/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/private/var/lib/hoobs/platforminsteonlocalbridge/node_modules/express/lib/router/index.js:341:12)
    at next (/private/var/lib/hoobs/platforminsteonlocalbridge/node_modules/express/lib/router/index.js:275:10)
    at query (/private/var/lib/hoobs/platforminsteonlocalbridge/node_modules/express/lib/middleware/query.js:45:5)
    at Layer.handle [as handle_request] (/private/var/lib/hoobs/platforminsteonlocalbridge/node_modules/express/lib/router/layer.js:95:5)

**Comment by i-did-that** [comment]
@kuestess  Sorry, I figured out I needed to manually add at least one device, then it loads.  
Donation coming your way!

**Comment by kuestess** [comment]
@i-did-that Many thanks!  Yep, you don't actually have to add any devices just as long as your config has the devices array (can be empty).  Glad you got it working!
