### ISSUE TITLE
Insteon.json not created, no localhost response to port 3000

### ISSUE THREAD

**Issue by ashbyjm** [kuestess/homebridge-platform-insteonlocal#202]
My Homebridge console on Win10 64-bit works fine at its own port 8581, but after installing the Insteonlocal platform I still can't run the InsteonUI on a web browser at port 3000. Every restart reports that it is creating a new insteon.json file.

Since I couldn't add devices in InsteonUI, I used the config editor to add a device called "Back Room".  My iPhone can connect and see devices, but nothing is activated. Homebridge shows "Error setting power state of Back Room", With Insteon apparently going belly-up, I currently have no controls. Any suggestions appreciated!

CONFIG.JSON
{
    "bridge": {
        "name": "Homebridge 546B",
        "username": "0E:38:82:9E:54:6B",
        "port": 51082,
        "pin": "375-95-924",
        "bind": [
            "Ethernet"
        ]
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "f",
            "lang": "auto",
            "platform": "config"
        },
        {
            "name": "InsteonLocal",
            "user": "Janet333",
            "pass": "xxxxxx",
            "host": "192.168.1.5",
            "port": "25105",
            "model": "2245",
            "refresh": "2",
            "server_port": "3000",
            "keepAlive": "3600",
            "devices": [
                {
                    "name": "Back Room",
                    "deviceID": "3E34C2",
                    "dimmable": "false",
                    "deviceType": "switch"
                }
            ],
            "platform": "InsteonLocal"
        }
    ]
}

**Comment by darkgod90** [comment]
+1 - have the same issue but on Linux

**Comment by darkgod90** [comment]
@ashbyjm  Fixed it - the username for the hub in the config was mispelled. After fixing it and restarting the process, a few new lines appeared in the log:

[4/19/2022, 2:37:18 AM] [InsteonLocal] Connected to Insteon Model 2245 Hub...
[4/19/2022, 2:37:18 AM] [InsteonLocal] Getting status for Test
[4/19/2022, 2:37:18 AM] [InsteonLocal] Insteon event listener started...
[4/19/2022, 2:37:18 AM] [InsteonLocal] Started Insteon Express server...
[4/19/2022, 2:37:28 AM] [InsteonLocal] Error getting power state of Test
[4/19/2022, 2:37:28 AM] [InsteonLocal] Hub/PLM id is 49ECF5

Bit counterintuitive that the server doesn't start unless you can connect to the hub, and that there are no error messages in the log file about user/pass being wrong. But, beggars can't be choosers ;)

**Comment by kuestess** [comment]
@darkgod90 You just beat me to it - from your log it wasn't connecting to the Hub - glad you got it fixed. @ashbyjm if you can post some output from your log, happy to troubleshoot.

**Comment by darkgod90** [comment]
> @darkgod90 You just beat me to it - from your log it wasn't connecting to the Hub - glad you got it fixed. @ashbyjm if you can post some output from your log, happy to troubleshoot.

Damn, you are fast! I do have a whole new issue after this though. It connects, but upon clicking "Get Hub Info" the server dies. 
Log file just keeps plotting the following until Homebridge restarts. Any idea?

TypeError: Cannot read properties of undefined (reading 'forEach')
    at buildDeviceTable (/usr/lib/node_modules/homebridge-platform-insteonlocal/insteon-ui.js:239:16)
    at InsteonUI.renderMainPage (/usr/lib/node_modules/homebridge-platform-insteonlocal/insteon-ui.js:185:2)
    at InsteonUI.handleRequest (/usr/lib/node_modules/homebridge-platform-insteonlocal/insteon-ui.js:1531:8)
    at Layer.handle [as handle_request] (/usr/lib/node_modules/homebridge-platform-insteonlocal/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/lib/node_modules/homebridge-platform-insteonlocal/node_modules/express/lib/router/index.js:323:13)
    at /usr/lib/node_modules/homebridge-platform-insteonlocal/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/lib/node_modules/homebridge-platform-insteonlocal/node_modules/express/lib/router/index.js:341:12)
    at next (/usr/lib/node_modules/homebridge-platform-insteonlocal/node_modules/express/lib/router/index.js:275:10)
    at expressInit (/usr/lib/node_modules/homebridge-platform-insteonlocal/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/usr/lib/node_modules/homebridge-platform-insteonlocal/node_modules/express/lib/router/layer.js:95:5)

**Comment by darkgod90** [comment]
Doing some research yields this: https://githublab.com/repository/activity/kuestess/homebridge-platform-insteonlocal.
Going through it, and I can confirm that I am using the latest version (where this bug is supposedly fixed).

**Comment by darkgod90** [comment]
Done some more research and found this one too: https://github.com/kuestess/homebridge-platform-insteonlocal/issues/169.
In here, @kuestess suggests to rename your insteon.json (its in the homebridge directory), restart homebridge, and then get hub info and devices again. However, I can't seem to find the "insteon.json" file anywhere.

**Comment by darkgod90** [comment]
@kuestess figured it out. There needs to be at least one device in the "devices" array or it won't work.

**Comment by ashbyjm** [comment]
I did an update to Insteonlocal this morning, but no change in behavior. Here's a screenshot with the log beginning with the restart request:
![Screenshot 2022-04-19 064558](https://user-images.githubusercontent.com/103968863/163996925-b4da1507-53b1-4687-a2dd-0cc115c0e7a3.jpg)
.

**Comment by kuestess** [comment]
@ashbyjm I don't see in your log where the plugin is connecting to the hub - can you provide the log from homebridge startup until you get the error messages? (the text is fine rather than screenshots).

**Comment by ashbyjm** [comment]
I agree. Here's the log for 1/2 day, beginning with the Insteonlocal update and restart:
[homebridge.log](https://github.com/kuestess/homebridge-platform-insteonlocal/files/8520872/homebridge.log)

**Comment by ashbyjm** [comment]
Here's a log immediately following a complete computer restart:

[37m[4/20/2022, 6:18:23 AM][0m [36m[HB Supervisor][0m OS: Windows_NT 10.0.19044 x64
[37m[4/20/2022, 6:18:23 AM][0m [36m[HB Supervisor][0m Node.js v16.14.2 C:\Program Files\nodejs\node.exe
[37m[4/20/2022, 6:18:23 AM][0m [36m[HB Supervisor][0m Homebridge Path: C:\Users\localadmin\AppData\Roaming\npm\node_modules\homebridge\bin\homebridge
[37m[4/20/2022, 6:18:23 AM][0m [36m[HB Supervisor][0m UI Path: C:\Users\localadmin\AppData\Roaming\npm\node_modules\homebridge-config-ui-x\dist\bin\standalone.js
[0;37m[4/20/2022, 6:18:27 AM] [0m[0;36m[Homebridge UI][0m [0;33mHomebridge Config UI X v4.43.0 is listening on :: port 8581[0m
[37m[4/20/2022, 6:18:28 AM][0m [36m[HB Supervisor][0m Starting Homebridge with extra flags: -I
[37m[4/20/2022, 6:18:28 AM][0m [36m[HB Supervisor][0m Started Homebridge v1.4.0 with PID: 11196
[37m[4/20/2022, 6:18:29 AM] [39mLoaded config.json with 0 accessories and 2 platforms.
[37m[4/20/2022, 6:18:29 AM] [39m---
[37m[4/20/2022, 6:18:29 AM] [39mLoaded plugin: homebridge-config-ui-x@4.43.0
[37m[4/20/2022, 6:18:29 AM] [39mRegistering platform 'homebridge-config-ui-x.config'
[37m[4/20/2022, 6:18:29 AM] [39m---
[37m[4/20/2022, 6:18:30 AM] [39mLoaded plugin: homebridge-platform-insteonlocal@0.4.24
homebridge API version: 2.7
[37m[4/20/2022, 6:18:30 AM] [39mRegistering platform 'homebridge-platform-insteonlocal.InsteonLocal'
[37m[4/20/2022, 6:18:30 AM] [39m---
[37m[4/20/2022, 6:18:30 AM] [39mLoading 2 platforms...
[37m[4/20/2022, 6:18:30 AM] [39m[36m[Config][39m Initializing config platform...
[37m[4/20/2022, 6:18:30 AM] [39m[36m[Config][39m Running in Service Mode
[37m[4/20/2022, 6:18:30 AM] [39m[36m[InsteonLocal][39m Initializing InsteonLocal platform...
Initializing Insteon UI 
Reading config from C:\Users\localadmin\.homebridge\config.json
Found 2 platform(s) in config
Creating new insteon.json
No devices in config
[37m[4/20/2022, 6:18:30 AM] [39m[36m[InsteonLocal][39m Started connection watcher...
[37m[4/20/2022, 6:18:30 AM] [39m[36m[InsteonLocal][39m Found 1 devices in config
[37m[4/20/2022, 6:18:30 AM] [39mInitializing platform accessory 'Back Room'...
Setup Payload:
X-HM://00243BDAS4OM2
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
[30m[47m                       [49m[39m
[30m[47m    ┌────────────┐     [49m[39m
[30m[47m    │ 375-95-924 │     [49m[39m
[30m[47m    └────────────┘     [49m[39m
[30m[47m                       [49m[39m
[37m[4/20/2022, 6:18:30 AM] [39mHomebridge v1.4.0 (HAP v0.10.0) (Homebridge 546B) is running on port 51082.

**Comment by ashbyjm** [comment]
Progress! Since I couldn't get the Express Server to respond to port 3000, I tried accessing the Insteon hub at IP:25105, no response- but it responded to 25104! I had previously configured it to 25105, so don't know what changed that. Changed the config.json and after a reboot, the Express Server responded!

I'll post an update after setting up my devices and testing.

**Comment by ashbyjm** [comment]
@kuestess Wow, this is awesome! After successfully running InsteonlocalUI, I understood that I was to manually edit config.json to include the additional devices that were now listed in insteon.json. A bit of copy/paste and a Homebridge restart, and everything I do in Apple Home is now showing up in reality! I have one device malfunctioning out of 7, but I'll figure that out.

Tips for other new users of your plug-in:
1. Before installing Homebridge, point a browser on your home nework to _yourhubIP#:25105_ to confirm that you get a username/password prompt, and test the credentials listed on the bottom of your Insteon hub. If your information is correct, you can proceed.
2. Run the installer per instructions for Homebridge.
3. From the plugins menu of Homebridge, search for and install the "Homebridge Platform Insteonlocal".
4. When prompted for an Insteon hub, fill-in the information you validated in step 1. You must also add the information for one device at this time, and be sure to save your entries. This should be enough to begin using InsteonUI to access your hub and assign friendly names to your devices. Your insteon.json file is saved through this tool. Follow the instructions carefully!
5. Open a non-formatting text editor to open insteon.json (in the same directory as config.json) and add additional devices to the config file- I used a combination of copy/paste and typing. Use a JSON validator on the file to debug syntax if needed.

**Comment by kuestess** [comment]
@ashbyjm Glad you got it working!  You can change the port in the Insteon app....but you know how that ends :-).  [](jsonlint.com) is a good online JSON validator if you're not familiar with the format.  Thanks for sharing tips!

**Comment by ashbyjm** [comment]
Yep, that's the one I used- saw it in one of your links. Of course, the Insteon app won't let you login to check the hub configuration, so I got the hint from my router's port forwarding configuration. Thanks for your help!

**Comment by ashbyjm** [comment]
Wonderful product!
