### ISSUE TITLE
Express server displaying error

### ISSUE THREAD

**Issue by mbcooper9734** [kuestess/homebridge-platform-insteonlocal#205]
I get the following using :3000 express server url

TypeError: Cannot read property 'forEach' of undefined
    at buildDeviceTable (/usr/lib/node_modules/homebridge-platform-insteonlocal/insteon-ui.js:239:16)
    at InsteonUI.renderMainPage (/usr/lib/node_modules/homebridge-platform-insteonlocal/insteon-ui.js:185:2)
    at InsteonUI.handleRequest (/usr/lib/node_modules/homebridge-platform-insteonlocal/insteon-ui.js:1531:8)
    at Layer.handle [as handle_request] (/usr/lib/node_modules/homebridge-platform-insteonlocal/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/lib/node_modules/homebridge-platform-insteonlocal/node_modules/express/lib/router/index.js:323:13)
    at /usr/lib/node_modules/homebridge-platform-insteonlocal/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/lib/node_modules/homebridge-platform-insteonlocal/node_modules/express/lib/router/index.js:341:12)
    at next (/usr/lib/node_modules/homebridge-platform-insteonlocal/node_modules/express/lib/router/index.js:275:10)
    at expressInit (/usr/lib/node_modules/homebridge-platform-insteonlocal/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/usr/lib/node_modules/homebridge-platform-insteonlocal/node_modules/express/lib/router/layer.js:95:5)

**Comment by kuestess** [comment]
@mbcooper9734 This is an issue that I need to fix - its because you don't have devices in your config.  As a workaround, you just need to add one device and it should work ok.

**Comment by mbcooper9734** [comment]
That worked.  You saved my ass. I have 9 clients down. I'm going to make
sure every one of them send you a donation as I bring the systems back up.

What's the best way to do that?

**Comment by kuestess** [comment]
@mbcooper9734 Glad that worked, and many thanks - there's a PayPal donation link on the main page or at [PayPal](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=AP4SUF96E39GU)
