### ISSUE TITLE
Scene Creation

### ISSUE THREAD

**Issue by dustinhood** [kuestess/homebridge-platform-insteonlocal#206]
Like many others I've had to make the move to local control of my Insteon 2245 hub.

I'm trying to create a scene in which links a SwitchLinc 2-Wire Dimmer to an Insteon Micro Dimmer.

I've selected the 2 devices from drop down lists, set a random group number not previously used "35", level values at "100", ramp rate ".01", the switch has been set as controller and the micro dimmer is set to responder.

![Screen Shot 2022-04-21 at 12 36 51 PM](https://user-images.githubusercontent.com/104167211/164539515-3236c37a-f900-43d9-a55b-3cfb7e19d2a5.png)

When I click the "Create Scene" button the following error is show in the Homebridge log window and no scene is created.

Building scene table for Bedroom Can lights...
[4/21/2022, 12:26:55 PM] TypeError: Cannot read properties of undefined (reading 'toUpperCase')
    at /usr/local/lib/node_modules/homebridge-platform-insteonlocal/insteon-ui.js:1693:57
    at Array.forEach (<anonymous>)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-platform-insteonlocal/insteon-ui.js:1688:17)
    at IncomingMessage.emit (node:events:526:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at IncomingMessage.Readable.push (node:internal/streams/readable:228:10)
    at HTTPParser.parserOnBody (node:_http_common:141:24)
[4/21/2022, 12:26:55 PM] Got SIGTERM, shutting down Homebridge...

![Screen Shot 2022-04-21 at 12 37 30 PM](https://user-images.githubusercontent.com/104167211/164539589-6ecde223-b9ba-4976-ad0f-eecb224251e3.png)

**Comment by kuestess** [comment]
@dustinhood Try going to the 'Hub' tab and clicking the 'Get Hub Info' button, then try to create your scene.  Working on a way to make this easier!

**Comment by dustinhood** [comment]
@kuestess tried your suggestion, unfortunately that also generated an error and crashed hombridge.

[4/21/2022, 5:50:07 PM] Homebridge v1.4.0 (HAP v0.10.0) (Homebridge 7614) is running on port 51014.
[4/21/2022, 5:50:07 PM] [InsteonLocal] Connected to Insteon Model 2245 Hub...
[4/21/2022, 5:50:07 PM] [InsteonLocal] Getting status for Front Door
[4/21/2022, 5:50:07 PM] [InsteonLocal] Insteon event listener started...
[4/21/2022, 5:50:07 PM] [InsteonLocal] Started Insteon Express server...
[4/21/2022, 5:50:08 PM] [InsteonLocal] Front Door is off at 0%
[4/21/2022, 5:50:08 PM] [InsteonLocal] Hub/PLM id is 455998
Building Hub scene data...
[
  { group: 2, controllers: [ [Object] ], responders: [] },
  { group: 3, controllers: [ [Object] ], responders: [] },
  { group: 4, controllers: [ [Object] ], responders: [ [Object] ] },
  { group: 5, controllers: [ [Object] ], responders: [ [Object] ] },
  { group: 6, controllers: [ [Object] ], responders: [ [Object] ] },
  { group: 7, controllers: [ [Object] ], responders: [ [Object] ] },
  { group: 13, controllers: [ [Object] ], responders: [ [Object] ] },
  {
    group: 17,
    controllers: [ [Object] ],
    responders: [ [Object], [Object] ]
  }
]
Building Hub scene data...
[
  { group: 2, controllers: [ [Object] ], responders: [] },
  { group: 3, controllers: [ [Object] ], responders: [] },
  { group: 4, controllers: [ [Object] ], responders: [ [Object] ] },
  { group: 5, controllers: [ [Object] ], responders: [ [Object] ] },
  { group: 6, controllers: [ [Object] ], responders: [ [Object] ] },
  { group: 7, controllers: [ [Object] ], responders: [ [Object] ] },
  { group: 13, controllers: [ [Object] ], responders: [ [Object] ] },
  {
    group: 17,
    controllers: [ [Object] ],
    responders: [ [Object], [Object] ]
  }
]
Getting Hub info
undefined
[4/21/2022, 5:50:52 PM] TypeError: Cannot read properties of undefined (reading 'id')
    at /usr/local/lib/node_modules/homebridge-platform-insteonlocal/insteon-ui.js:1588:20
    at /usr/local/lib/node_modules/homebridge-platform-insteonlocal/node_modules/q/q.js:2055:17
    at runSingle (/usr/local/lib/node_modules/homebridge-platform-insteonlocal/node_modules/q/q.js:137:13)
    at flush (/usr/local/lib/node_modules/homebridge-platform-insteonlocal/node_modules/q/q.js:125:13)
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
    at runNextTicks (node:internal/process/task_queues:65:3)
    at processTimers (node:internal/timers:499:9)
[4/21/2022, 5:50:52 PM] Got SIGTERM, shutting down Homebridge...

![Screen Shot 2022-04-21 at 5 52 19 PM](https://user-images.githubusercontent.com/104167211/164575811-9863aa60-e476-4b7e-bf49-f22b9235c00d.png)

I worked around the scene creation issue by linking the two devices directly together bypassing the hub. I pressed the set button on the switch (controller device) until it beeped, then pressed the set button on the micro dimmer (responder) until it beeped. The switch is now synced to the micro controller.

The ability to do this in the web browser without having to get a ladder and be at each device would be super helpful.

**Comment by kuestess** [comment]
@dustinhood Interesting - looking at your log, nothing is returned from the info request to the Hub, however earlier in the log  it says 'Hub/PLM id is 455998'.  Both of those use the same function, but its not working on the button click....let me try something.
