### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined — restarts Homebridge

### ISSUE THREAD

**Issue by aketterson** [kuestess/homebridge-platform-insteonlocal#219]
Every several minutes the following fatal error is generated that cause Homebridge to restart.  Any thought where I should look to correct?

[01/05/2022, 16:02:06] TypeError: Cannot read property 'name' of undefined
                    at /usr/local/lib/node_modules/homebridge-platform-insteonlocal/index.js:2473:58
		    at Array.forEach (<anonymous>)
		    at InsteonLocalAccessory.getGroupMemberStatus (/usr/local/lib/node_modules/homebridge-platform-insteonlocal/index.js:2464:20)
		    at Insteon.<anonymous> (/usr/local/lib/node_modules/homebridge-platform-insteonlocal/index.js:734:40)
		    at Insteon.emit (events.js:315:20)
		    at Insteon.handler (/usr/local/lib/node_modules/homebridge-platform-insteonlocal/node_modules/home-controller/lib/Insteon/index.js:725:12)
		    at Insteon._checkStatus (/usr/local/lib/node_modules/homebridge-platform-insteonlocal/node_modules/home-controller/lib/Insteon/index.js:667:33)
		    at Insteon.checkStatus (/usr/local/lib/node_modules/homebridge-platform-insteonlocal/node_modules/home-controller/lib/Insteon/index.js:603:21)
		    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-platform-insteonlocal/node_modules/home-controller/lib/Insteon/index.js:615:16)
  			  at listOnTimeout (internal/timers.js:554:17)

**Comment by kuestess** [comment]
@aketterson Looks like an issue with how group members are defined - can you post your config?

**Comment by dhughestrimark** [comment]
I'm seeing the same issue - here is my config (username and password removed):

{
    "name": "InsteonLocal",
    "user": "",
    "pass": "",
    "host": "192.168.1.65",
    "port": "25105",
    "model": "2245",
    "refresh": "0",
    "server_port": "3000",
    "keepAlive": "3600",
    "platform": "InsteonLocal"
}

**Comment by dhughestrimark** [comment]
Homebridge config:

{
    "bridge": {
        "name": "Homebridge 7387",
        "username": "0E:0D:63:B8:73:87",
        "port": 51812,
        "pin": "786-91-002",
        "advertiser": "bonjour-hap"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "name": "InsteonLocal",
            "user": "",
            "pass": "",
            "host": "192.168.1.65",
            "port": "25105",
            "model": "2245",
            "refresh": "0",
            "server_port": "3000",
            "keepAlive": "3600",
            "platform": "InsteonLocal"
        }
    ]
}

**Comment by aketterson** [comment]
[config (insteon).txt](https://github.com/kuestess/homebridge-platform-insteonlocal/files/8628246/config.insteon.txt)
Thanks @kuestess:
Attached is my insteon-related config file?

Any thoughts?

**Comment by aketterson** [comment]
This might be a clue in the error log right before the homebridge restarts...

[04/05/2022, 20:33:53] [Insteon Local Platform] Error getting power state of China Cabinet
[04/05/2022, 20:34:01] [homebridge-platform-insteonlocal] This plugin generated a warning from the characteristic 'Brightness': Characteristic not in required or optional characteristic section for service Switch. Adding anyway.. See https://homebridge.io/w/JtMGR for more info.
[04/05/2022, 20:35:49] [Insteon Local Platform] Getting status of scene device Office Lamp
[04/05/2022, 20:35:49] TypeError: Cannot read property 'name' of undefined

**Comment by kuestess** [comment]
@aketterson Something strange going on here - can you run homebridge in debug mode `homebridge -D` and post the output when you get one of these errors?

**Comment by aketterson** [comment]
> 
@kuestess 
See if this attached log file is of any help
[homebridge_restart.log.docx](https://github.com/kuestess/homebridge-platform-insteonlocal/files/8647800/homebridge_restart.log.docx)
p

**Comment by kuestess** [comment]
@aketterson Try removing the periods in the device ids for the `groupMembers` part of the config and see if that takes care of the issue.

**Comment by aketterson** [comment]
@kuestess   - I never had any periods in the IDs of my <groupMembers>.  When I get a chance, I'll do more investigative work.  I assume the debug file did not give you any clues.
