### ISSUE TITLE
Crash when "groupMembers" is configured.

### ISSUE THREAD

**Issue by sahafeez** [kuestess/homebridge-platform-insteonlocal#239]
So I added groupMembers for switches that are linked so the status will update per the wiki. Not sure if you need both IDs (self, and other members) but it crashes either way.
```
                {
                    "name": "Garage Office.Door",
                    "deviceID": "42.9C.D5",
                    "dimmable": "yes",
                    "deviceType": "dimmer",
                    "groupMembers": "42.9C.D5,42.A5.D3"
                },
                {
                    "name": "Garage Office.Garage",
                    "deviceID": "42.A5.D3",
                    "dimmable": "yes",
                    "deviceType": "dimmer",
                    "groupMembers": "42.9C.D5,42.A5.D3"
                },
```

So triggering the device results in:

```
[5/8/2022, 10:33:32 AM] [InsteonLocal] Got off event for Garage Office.Door

/usr/lib/node_modules/homebridge-platform-insteonlocal/index.js:2469
        self.groupMembers.forEach(function(deviceID){
                   ^
TypeError: Cannot read properties of undefined (reading 'name')
    at /usr/lib/node_modules/homebridge-platform-insteonlocal/index.js:2478:58
    at Array.forEach (<anonymous>)
    at InsteonLocalAccessory.getGroupMemberStatus (/usr/lib/node_modules/homebridge-platform-insteonlocal/index.js:2469:20)
    at Insteon.<anonymous> (/usr/lib/node_modules/homebridge-platform-insteonlocal/index.js:608:43)
    at Insteon.emit (node:events:527:28)
    at Insteon.handler (/usr/lib/node_modules/homebridge-platform-insteonlocal/node_modules/home-controller/lib/Insteon/index.js:725:12)
    at Insteon._checkStatus (/usr/lib/node_modules/homebridge-platform-insteonlocal/node_modules/home-controller/lib/Insteon/index.js:667:33)
    at Insteon.checkStatus (/usr/lib/node_modules/homebridge-platform-insteonlocal/node_modules/home-controller/lib/Insteon/index.js:603:21)
    at SerialPort.<anonymous> (/usr/lib/node_modules/homebridge-platform-insteonlocal/node_modules/home-controller/lib/Insteon/index.js:165:12)
    at SerialPort.emit (node:events:527:28)
[5/8/2022, 10:33:32 AM] [InsteonLocal] Child bridge process ended
[5/8/2022, 10:33:32 AM] [InsteonLocal] Process Ended. Code: 1, Signal: null
[5/8/2022, 10:33:39 AM] [InsteonLocal] Restarting Process...
[5/8/2022, 10:33:42 AM] [InsteonLocal] Launched child bridge with PID 2420
homebridge API version: 2.7
```

**Comment by sahafeez** [comment]
Okay, removed the XX.XX.XX format to XXXXXX then it works. :)

**Comment by kuestess** [comment]
@sahafeez Did you only remove the periods from the group members, or also from the deviceID?  This looks very similar to #219.

**Comment by sahafeez** [comment]
Just the IDs used in the groupMembers section.

```
                {
                    "name": "Garage Office.Door",
                    "deviceID": "42.9C.D5",
                    "dimmable": "yes",
                    "deviceType": "dimmer",
                    "controllers": [
                        "42A5D3"
                    ],
                    "groupMembers": "429CD5,42A5D3"
                },
                {
                    "name": "Garage Office.Garage",
                    "deviceID": "42.A5.D3",
                    "dimmable": "yes",
                    "deviceType": "dimmer",
                    "controllers": [
                        "429CD5"
                    ],
                    "groupMembers": "429CD5,42A5D3"
                },
```

So the nice thing is with this setup the accessories pages seems to update correctly when a single member is physically triggered.
