### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'id')

### ISSUE THREAD

**Issue by coreTech51** [kuestess/homebridge-platform-insteonlocal#282]
Plugin not functioning. (See attachment) I'm running homebridge-platform-insteonlocal v0.5.4-3
It will start, state "Loading accessory from cache", then say the number found, then "Restoring existing accessory from cache", then state "Homebridge v1.5.1 (HAP v0.10.4) (InsteonLocal) is running on port 56513.
[11/12/2022, 8:34:30 AM] [InsteonUI] Hub/PLM info is {
  raw: '02603C98480333A5',
  type: '60',
  id: '3C9848',
  deviceCategory: { id: 3, name: 'Network Bridges' },
  deviceSubcategory: { id: 51 },
  firmwareVersion: 'A5'
}"
and then list "error getting power states". 

Next it will state: [homebridge-platform-insteonlocal] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://homebridge.io/w/JtMGR for more info.
[homebridge-platform-insteonlocal] This plugin generated a warning from the characteristic 'Rotation Speed': characteristic value expected valid finite number and received "undefined" (undefined). See https://homebridge.io/w/JtMGR for more info.

Next this will happen:
/var/lib/homebridge/node_modules/homebridge-platform-insteonlocal/node_modules/q/q.js:137
            task();
            ^
TypeError: Cannot read properties of undefined (reading 'id')
    at /var/lib/homebridge/node_modules/homebridge-platform-insteonlocal/src/InsteonLocalPlatform.ts:120:27
    at /var/lib/homebridge/node_modules/homebridge-platform-insteonlocal/node_modules/q/q.js:2055:17
    at runSingle (/var/lib/homebridge/node_modules/homebridge-platform-insteonlocal/node_modules/q/q.js:137:13)
    at flush (/var/lib/homebridge/node_modules/homebridge-platform-insteonlocal/node_modules/q/q.js:125:13)
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
[InsteonLocal] Child bridge process ended
[InsteonLocal] Process Ended. Code: 1, Signal: null
[InsteonLocal] Restarting Process...
[InsteonLocal] Launched child bridge with PID 9610
[Insteon UI Error.pdf](https://github.com/kuestess/homebridge-platform-insteonlocal/files/9995120/Insteon.UI.Error.pdf)

**Comment by kuestess** [comment]
@coreTech51 Can you post your config?  Any recent changes to your config?

**Comment by coreTech51** [comment]
Everything was working fine. I made no big changes except for adding a few new devices and changing some names of devices. I did notice that when I changed the name it added a new device with the changed name in HomeBridge and not only changed the name. I’m using HomeBridge v1.5.1. Here’s my configuration. (See PDF). Aaron Sent from my iPadMiniAaron ***@***.*** Notice: This communication, including attachments, may contain information that is confidential and protected by the attorney/client or other privileges. It constitutes non-public information intended to be conveyed only to the designated recipient(s). If reader or recipient of this communication is not the intended recipient, an employee or agent of the intended recipient who is responsible for delivering it to the intended recipient, or you believe that you have received this communication in error, please notify the sender immediately by return email and promptly delete this email, including attachments without reading or saving them in any manner. The unauthorized use, dissemination, distribution, or reproduction of this email, including attachments, is prohibited and may be unlawful. Receipt by anyone other than the intended recipient(s) is not a waiver of any attorney/client or other privilege.---------------------------------------------On Nov 13, 2022, at 3:47 PM, kuestess ***@***.***> wrote:﻿
@coreTech51 Can you post your config?  Any recent changes to your config?

**Comment by coreTech51** [comment]
I haven’t heard back from you so, ﻿I’m sending this to you again. Also, are there instructions on how to use your plugin with a PLM? If I can not get things working properly with the Insteon hub, I like to switch to my PLM 2413U.Aaron “Everything was working fine. I made no big changes except for adding a few new devices and changing some names of devices. I did notice that when I changed the name it added a new device with the changed name in HomeBridge and not only changed the name. I’m using HomeBridge v1.5.1. Here’s my configuration. (See PDF).”Aaron Sent from my iPadMiniAaron ***@***.*** Notice: This communication, including attachments, may contain information that is confidential and protected by the attorney/client or other privileges. It constitutes non-public information intended to be conveyed only to the designated recipient(s). If reader or recipient of this communication is not the intended recipient, an employee or agent of the intended recipient who is responsible for delivering it to the intended recipient, or you believe that you have received this communication in error, please notify the sender immediately by return email and promptly delete this email, including attachments without reading or saving them in any manner. The unauthorized use, dissemination, distribution, or reproduction of this email, including attachments, is prohibited and may be unlawful. Receipt by anyone other than the intended recipient(s) is not a waiver of any attorney/client or other privilege.---------------------------------------------On Nov 13, 2022, at 3:47 PM, kuestess ***@***.***> wrote:﻿
@coreTech51 Can you post your config?  Any recent changes to your config?

**Comment by kuestess** [comment]
@coreTech51 Can you repost your config (don't see it attached).  Interesting that it just started happening without any significant changes...have you tried restarting your hub?

**Comment by coreTech51** [comment]
[TypeError: Cannot read properties of undefined (reading 'id') (Issue….pdf](https://github.com/kuestess/homebridge-platform-insteonlocal/files/10075543/TypeError.Cannot.read.properties.of.undefined.reading.id.Issue.pdf)

**Comment by kuestess** [comment]
@coreTech51 This one's a little hard to diagnose, but looks like your hub isn't responding to a request for info.  I removed some duplicate calls in the version I just published that should help.  Give it a try and let me know if that works.  The latest release should also fix the issue with renaming/removing accessories.

**Comment by coreTech51** [comment]
Thanks. I'll update and monitor its function.

**Comment by JimCSaratoga** [comment]
@kuestess working like a charm !  Quick question I'm noticing a lot of old Insteon ID's showing up in the config device pulls on the portal at homebridge:3000 - can you remind me how to delete that file and pull it fresh from the hub?

**Comment by coreTech51** [comment]
The issue with renaming/removing accessories seem to be fixed, but I'm still having an issue with connecting to the hub. I went into the InsteonUI - Configuration to see the Hub Information, which I can, but I'm getting little to no "linked devices". This message comes up "Links No links in Insteon config - please click Get Links to get links and devices from Hub". I would restart the Hub, unplug and plug back in. What could this be? Thanks for your help.

**Comment by kuestess** [comment]
@coreTech51 Sounds like the ui loads and you're not getting the same error (as above) anymore?  If you don't have any linked devices, then you may need to get hub info again, or get devices again on the device page.
