### ISSUE TITLE
Plugin crashes homebridge with AssertionError

### ISSUE THREAD

**Issue by Rink73** [kuestess/homebridge-platform-insteonlocal#292]
Old hub crashed, so I have a whole new 2245 hub.  Upon installing plugin and adding credentials (without manually adding any devices), I get the following:

[2/8/2023, 7:34:21 AM] AssertionError [ERR_ASSERTION]: Cannot generate setupURI on an accessory that isn't published yet!
    at Bridge.Accessory.setupURI (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:994:11)
    at Server.setServerStatus (/usr/local/lib/node_modules/homebridge/src/server.ts:155:45)
    at Server.teardown (/usr/local/lib/node_modules/homebridge/src/server.ts:199:10)
    at signalHandler (/usr/local/lib/node_modules/homebridge/src/cli.ts:93:12)
    at process.emit (node:events:390:28)
    at process.emit (/usr/local/lib/node_modules/homebridge/node_modules/source-map-support/source-map-support.js:516:21)
[2/8/2023, 7:34:21 AM] [InsteonLocal] Connected to Insteon Model 2245 Hub...

I have the entire hub setup within the Director app with devices and scenes, and everything works great.  When looking through the logs, it does list all the devices that I have on the hub, but continues to crash the whole homebridge docker, forcing a continual reboot.

Any help is greatly appreciated!!!!

**Comment by Rink73** [comment]
Another error in the log file:

[2/8/2023, 7:00:02 AM] [InsteonLocal] Found 1 devices in config
[2/8/2023, 7:00:02 AM] TypeError: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at new NodeError (node:internal/errors:372:5)
    at Hash.update (node:internal/crypto/hash:105:11)
    at Object.generate (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/uuid.ts:11:11)
    at InsteonLocalPlatform.discoverDevices (/homebridge/node_modules/homebridge-platform-insteonlocal/src/InsteonLocalPlatform.ts:648:38)
    at HomebridgeAPI.<anonymous> (/homebridge/node_modules/homebridge-platform-insteonlocal/src/InsteonLocalPlatform.ts:116:12)
    at HomebridgeAPI.emit (node:events:539:35)
    at HomebridgeAPI.signalFinished (/usr/local/lib/node_modules/homebridge/src/api.ts:275:10)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:190:14)

Both of these errors only pop up when I enable/connect the Insteon plugin.

**Comment by kuestess** [comment]
@Rink73 Haven't seen this one before :-) - can you post your config?

**Comment by languy99** [comment]
Hello 

I have this same error. Any update on what it could be? 

[1/27/2024, 12:45:21 AM] [InsteonLocal] Initializing InsteonLocal platform...
[1/27/2024, 12:45:21 AM] [InsteonUI] Initializing Insteon UI 
[1/27/2024, 12:45:21 AM] [InsteonUI] Reading config from /var/lib/homebridge/config.json
[1/27/2024, 12:45:21 AM] [InsteonUI] Found 3 platform(s) in config
[1/27/2024, 12:45:21 AM] [InsteonUI] Reading devices from insteon.json
[1/27/2024, 12:45:21 AM] [InsteonUI] Done with InsteonUI init
[1/27/2024, 12:45:21 AM] [InsteonLocal] Found 1 devices in config
[1/27/2024, 12:45:21 AM] TypeError: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at Hash.update (node:internal/crypto/hash:104:11)
    at Object.generate (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/uuid.ts:11:11)
    at InsteonLocalPlatform.discoverDevices (/var/lib/homebridge/node_modules/homebridge-platform-insteonlocal/src/InsteonLocalPlatform.ts:659:38)
    at HomebridgeAPI.<anonymous> (/var/lib/homebridge/node_modules/homebridge-platform-insteonlocal/src/InsteonLocalPlatform.ts:116:12)
    at HomebridgeAPI.emit (node:events:530:35)
    at HomebridgeAPI.signalFinished (/var/lib/homebridge/node_modules/homebridge/src/api.ts:275:10)
    at Server.start (/var/lib/homebridge/node_modules/homebridge/src/server.ts:190:14)

**Comment by kuestess** [comment]
@languy99 Make sure you have a name defined for the device in your config.
