### ISSUE TITLE
Serial Port Not Supported

### ISSUE THREAD

**Issue by Jmakosky** [kuestess/homebridge-platform-insteonlocal#299]
Kuestess,
You were helping me last week with InsteonLocal detecting my PLM hub via the serial port.  I ended up deleting and reinstalling NODE.JS, NPM, Homebridge and finally your plugin.  Unfortunately, nothing has changed.  I ran some of the commands you provided during our troubleshooting as well.  I am at a complete loss.  The hub and usb serial port works because I can enable Indigodomo and use it to control all the insteon devices.  I am being careful of stopping the Indigo server so the port doesn't conflict.  I verified the path to the port as well "/dev/tty.usbserial_A906XMJE" and made sure it is correct in the plugin.

I don't know what to do.  I am not sure if I re-ran all the commands you had sent me such as the one to revert back to the old port or something like that.  I feel like a complete Noob here.  Your plugin had worked great for six months.  Did something change in the i3 update you just sent out.  My issues started at somewhere around that point but I was gone for a week so it is a little foggy.  After I updated the plugin I didn't reboot the computer but a few days later the Mac Mini updated, rebooted and I have had the problem since then.  So, either the MacOS update got me or the update to the plugin. 
I have a M1 Mac Mini currently running Ventura 13.4.1.
Thoughts?  

---------------------------------------------------------------------------------------
Registering platform 'homebridge-platform-insteonlocal.InsteonLocal'
[8/10/2023, 7:24:06 PM] [InsteonLocal] Loaded homebridge-platform-insteonlocal v0.5.10 child bridge successfully

/usr/local/lib/node_modules/homebridge-platform-insteonlocal/node_modules/home-controller/lib/Insteon/index.js:123
    throw (new Error('serial is Unsupported on this platform'));
           ^
Error: serial is Unsupported on this platform
    at Insteon.serial (/usr/local/lib/node_modules/homebridge-platform-insteonlocal/node_modules/home-controller/lib/Insteon/index.js:123:12)
    at InsteonLocalPlatform.connectToHub (/usr/local/lib/node_modules/homebridge-platform-insteonlocal/src/InsteonLocalPlatform.ts:212:11)
    at new InsteonLocalPlatform (/usr/local/lib/node_modules/homebridge-platform-insteonlocal/src/InsteonLocalPlatform.ts:91:10)
    at ChildBridgeFork.startBridge (/usr/local/lib/node_modules/homebridge/src/childBridgeFork.ts:150:42)
[8/10/2023, 7:24:06 PM] [InsteonLocal] Child bridge process ended
[8/10/2023, 7:24:06 PM] [InsteonLocal] Process Ended. Code: 1, Signal: null

**Comment by kuestess** [comment]
@Jmakosky I have a similar setup to you - M1 studio + PLM - that I was able to test with.  I uninstalled everything plugin-related to simulate a new setup and was able to get it up and running fine just by installing the plugin via `npm i -g home bridge-platform-insteonlocal`.  Not sure exactly what the issue is with your setup, but perhaps try installing a current version of node with nvm ([https://github.com/nvm-sh/nvm](https://github.com/nvm-sh/nvm)) and then reinstall the plugin.  I highly recommend nvm as it makes it super easy to install node (make sure to uninstall you existing node setup first).  I happen to be running node v16.15.0, but any recent version should be fine.  Using nvm, you can just run `nvm install node --lts` to get the latest.

**Comment by Jmakosky** [comment]
Which means I will lose everything again but I am willing because half my
house or more is on insteon and I am hurting without this working.  Turning
a switch on manually is so hard versus using Siri! :"))
I am guessing that I somehow *did not delete* "Everything" related to
node.js, NPM, and Homebridge.  I researched it on the internet and used all
the instructions I could find but I feel like I still missed some
directories along the way and my "reinstall" was for not.
Do you have any recommendations on how to delete everything node, npm,
homebridge, etc?  Given you just tried it./did it, I am hoping you can give
me some pointers.  Paths/directories would be awesome.

**Comment by kuestess** [comment]
@Jmakosky First world problems, huh?! :-).  You shouldn't lose your homebridge configuration as there's no need to uninstall homebridge.  That config is typically in your user directory in `.homebridge`.  Check to see if it's there and create a copy of it first.  Here's what I'd do:

1. Uninstall your existing node packages: `npm uninstall homebridge-platform-insteonlocal serialport`
2. Uninstall your existing node: type `which node` and then `rm [output from last command]`
3. Install nvm: `curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.4/install.sh | bash`. Close and re-open your terminal after this.
4. Install latest node LTS version: `nvm install node --lts` then `nvm use node`
5. Reinstall homebridge and the plugin: `npm i -g homebridge homebridge-platform-insteonlocal `

This is from memory - it should work, but let me know if you have questions.

**Comment by Jmakosky** [comment]
Kuestess,
Success!  I spent four hours on it yesterday and finally got it working
again.  I first followed your directions above but that didn't seem to
work.    I blame it on being a noob more than anything.  It said I had
multiple copies between NPM and NVM, etc.  It might have worked but it just
came up with too many errors and issues that I stopped and decided to nuke
all of homebridge again.
So I found another website that provided some commands for this
situation and that seemed to clean it all off.  I also had to install Xcode
which my computer didn't have.
Ultimately, this is what I would say happened. When my MAC Mini updated, it
changed the path to the USB device ever so slightly.  It was so close I
didn't notice.  I ran this command below to find the path and *copy/pasted
it directly into your hub config, rebooted* and it came alive.
[image: image.png]
I had to page thru lots of lines but the path is there for all the
connected devices.
But then Homebridge wouldn't let me reinstall my other plugins because it
said they were already installed.  So I ran this command which seem to
allow me to reinstall them again.
[image: image.png]
Afterwards I found out all I had to do was go into Homebridge config and
"Reset" it to remove the bridge to homekit.  That would have allowed me to
reinstall the plugin - I guess.
At this point, your plugin, Homebridge Scheduler, Dummy, & MagicHome are
all functional again.   But, not all is perfect, the log has errors
indicating it thinks one of my Insteon light switches is a KeyPad.  Never
seen that one before.  Config for the device seems correct in the plugin
but I will search around some more.  Everything on the hub seems right so I
don't know where that is coming from.

**Comment by kuestess** [comment]
@Jmakosky You should be able to correct the device definition in your config - you can edit that device in the gui to change the deviceType to `lightbulb` instead of a `keypad`
