### ISSUE TITLE
Insteon scenes crash homebridge

### ISSUE THREAD

**Issue by jeffwhalen** [kuestess/homebridge-platform-insteonlocal#30]
Everytime I use an Insteon scene i added to homebridge In the home app it crashes Homebridge. Any idea what’s going on here?

**Comment by kuestess** [comment]
@jeffwhalen Can you post your config and the crash output from homebridge in debug mode? (homebridge -D)

**Comment by jeffwhalen** [comment]
Heres the Debug Report:

[9/21/2018, 7:35:05 AM] Homebridge is running on port 51826.
[9/21/2018, 7:35:05 AM] [Insteon Local Platform] Porch Light is off at 0%
[9/21/2018, 7:35:05 AM] [Insteon Local Platform] Game Room Lamp is off at 0%
[9/21/2018, 7:35:05 AM] [Insteon Local Platform] Game Room Fan Light is off at 0%
[9/21/2018, 7:35:06 AM] [Insteon Local Platform] Kitchen is off at 0%
[9/21/2018, 7:35:06 AM] [Insteon Local Platform] Bedroom Lamp 2 is off at 0%
[9/21/2018, 7:35:07 AM] [Insteon Local Platform] Bedroom Lamp 1 is off at 0%
[9/21/2018, 7:35:07 AM] [Insteon Local Platform] Bedroom Fan Light is off at 0%
[9/21/2018, 7:35:08 AM] [Insteon Local Platform] Living Room Fan Light is off at 0%
[9/21/2018, 7:35:08 AM] [Insteon Local Platform] Living Room Lamp 1 is off at 0%
[9/21/2018, 7:35:08 AM] [Insteon Local Platform] Living Room Lamp 2 is off at 0%
[9/21/2018, 7:35:09 AM] [Insteon Local Platform] Living Room Lamp 3 is off at 0%
[9/21/2018, 7:35:09 AM] [Insteon Local Platform] Sink Light is off at 0%
[9/21/2018, 7:35:09 AM] [Insteon Local Platform] Sconces is off at 0%
[9/21/2018, 7:35:10 AM] [Insteon Local Platform] Avery Room is off at 0%
[9/21/2018, 7:35:10 AM] [Insteon Local Platform] Keagan Room is off at 0%
[9/21/2018, 7:35:10 AM] [Insteon Local Platform] Cabinet Lights is off at 0%
[9/21/2018, 7:35:10 AM] [Insteon Local Platform] Hall Light is off at 0%
[9/21/2018, 7:35:10 AM] [Insteon Local Platform] Bedroom Fan is off at 0%
[9/21/2018, 7:35:11 AM] [Insteon Local Platform] Living Room Fan is on at 100%
[9/21/2018, 7:35:11 AM] [Insteon Local Platform] Butlers Pantry is off at 0%
[9/21/2018, 7:35:11 AM] [Insteon Local Platform] Butlers Pantry Lamp is off at 0%
[9/21/2018, 7:35:12 AM] [Insteon Local Platform] Dining Room is off at 0%
[9/21/2018, 7:35:12 AM] [Insteon Local Platform] Front Hall Lamp is off at 0%
[9/21/2018, 7:35:13 AM] [Insteon Local Platform] Porch Light is off at 0%
[9/21/2018, 7:35:13 AM] [Insteon Local Platform] Game Room Lamp is off at 0%
[9/21/2018, 7:35:13 AM] [Insteon Local Platform] Game Room Fan Light is off at 0%
[9/21/2018, 7:35:13 AM] [Insteon Local Platform] Kitchen is off at 0%
[9/21/2018, 7:35:14 AM] [Insteon Local Platform] Bedroom Lamp 2 is off at 0%
[9/21/2018, 7:35:14 AM] [Insteon Local Platform] Bedroom Lamp 1 is off at 0%
[9/21/2018, 7:35:14 AM] [Insteon Local Platform] Bedroom Fan Light is off at 0%
[9/21/2018, 7:35:15 AM] [Insteon Local Platform] Living Room Fan Light is off at 0%
[9/21/2018, 7:35:15 AM] [Insteon Local Platform] Living Room Lamp 1 is off at 0%
[9/21/2018, 7:35:15 AM] [Insteon Local Platform] Living Room Lamp 2 is off at 0%
[9/21/2018, 7:35:16 AM] [Insteon Local Platform] Living Room Lamp 3 is off at 0%
[9/21/2018, 7:35:16 AM] [Insteon Local Platform] Sink Light is off at 0%
[9/21/2018, 7:35:16 AM] [Insteon Local Platform] Butlers Pantry Lamp 2 is off at 0%
[9/21/2018, 7:35:17 AM] [Insteon Local Platform] Sconces is off at 0%
[9/21/2018, 7:35:17 AM] [Insteon Local Platform] Setting power state of All Off to on
[9/21/2018, 7:35:17 AM] [Insteon Local Platform] State: true
[9/21/2018, 7:35:22 AM] [Insteon Local Platform] Binary map: 11100000
[9/21/2018, 7:35:22 AM] [Insteon Local Platform] Button D state is off
[9/21/2018, 7:35:22 AM] [Insteon Local Platform] All Off is off
[9/21/2018, 7:35:23 AM] [Insteon Local Platform] Received command for 1AF4CD
[9/21/2018, 7:35:23 AM] [Insteon Local Platform] Found 1 accessories matching 1AF4CD
[9/21/2018, 7:35:23 AM] [Insteon Local Platform] Hub command: {"standard":{"type":"50","id":"1AF4CD","gatewayId":"4D6EE4","extended":false,"messageType":3,"hopsLeft":0,"maxHops":0,"command1":"11","command2":"1B","raw":"02501AF4CD4D6EE460111B"}}
[9/21/2018, 7:35:23 AM] [Insteon Local Platform] Got event for Living Room Lamp 3
[9/21/2018, 7:35:23 AM] [Insteon Local Platform] Got on event for Living Room Lamp 3
[9/21/2018, 7:35:23 AM] [Insteon Local Platform] Received command for 2C147E
[9/21/2018, 7:35:23 AM] [Insteon Local Platform] Found 1 accessories matching 2C147E
[9/21/2018, 7:35:23 AM] [Insteon Local Platform] Hub command: {"standard":{"type":"50","id":"2C147E","gatewayId":"4D6EE4","extended":false,"messageType":3,"hopsLeft":0,"maxHops":0,"command1":"11","command2":"1B","raw":"02502C147E4D6EE460111B"}}
[9/21/2018, 7:35:23 AM] [Insteon Local Platform] Got event for Living Room Lamp 1
[9/21/2018, 7:35:23 AM] [Insteon Local Platform] Got on event for Living Room Lamp 1
[9/21/2018, 7:35:23 AM] [Insteon Local Platform] Received command for 235EFA
[9/21/2018, 7:35:23 AM] [Insteon Local Platform] Found 1 accessories matching 235EFA
[9/21/2018, 7:35:23 AM] [Insteon Local Platform] Hub command: {"standard":{"type":"50","id":"235EFA","gatewayId":"4D6EE4","extended":false,"messageType":3,"hopsLeft":0,"maxHops":0,"command1":"11","command2":"1B","raw":"0250235EFA4D6EE460111B"}}
[9/21/2018, 7:35:23 AM] [Insteon Local Platform] Got event for Living Room Lamp 2
[9/21/2018, 7:35:23 AM] [Insteon Local Platform] Got on event for Living Room Lamp 2
[9/21/2018, 7:35:23 AM] [Insteon Local Platform] Received command for 1DFCFB
[9/21/2018, 7:35:23 AM] [Insteon Local Platform] Found 1 accessories matching 1DFCFB
[9/21/2018, 7:35:23 AM] [Insteon Local Platform] Hub command: {"standard":{"type":"50","id":"1DFCFB","gatewayId":"4D6EE4","extended":false,"messageType":3,"hopsLeft":0,"maxHops":1,"command1":"11","command2":"1B","raw":"02501DFCFB4D6EE461111B"}}
[9/21/2018, 7:35:23 AM] [Insteon Local Platform] Got event for Living Room Fan Light
[9/21/2018, 7:35:23 AM] [Insteon Local Platform] Got on event for Living Room Fan Light
[9/21/2018, 7:35:23 AM] [Insteon Local Platform] Received command for 1D4990
[9/21/2018, 7:35:23 AM] [Insteon Local Platform] Found 1 accessories matching 1D4990
[9/21/2018, 7:35:23 AM] [Insteon Local Platform] Hub command: {"standard":{"type":"50","id":"1D4990","gatewayId":"4D6EE4","extended":false,"messageType":3,"hopsLeft":0,"maxHops":0,"command1":"11","command2":"1B","raw":"02501D49904D6EE460111B"}}
[9/21/2018, 7:35:23 AM] [Insteon Local Platform] Got event for Dining Room
[9/21/2018, 7:35:23 AM] [Insteon Local Platform] Got on event for Dining Room
[9/21/2018, 7:35:24 AM] [Insteon Local Platform] Received command for 2A5227
[9/21/2018, 7:35:24 AM] [Insteon Local Platform] Found 1 accessories matching 2A5227
[9/21/2018, 7:35:24 AM] [Insteon Local Platform] Hub command: {"standard":{"type":"50","id":"2A5227","gatewayId":"4D6EE4","extended":false,"messageType":3,"hopsLeft":0,"maxHops":0,"command1":"11","command2":"1B","raw":"02502A52274D6EE460111B"}}
[9/21/2018, 7:35:24 AM] [Insteon Local Platform] Got event for Porch Light
[9/21/2018, 7:35:24 AM] [Insteon Local Platform] Got on event for Porch Light
[9/21/2018, 7:35:24 AM] [Insteon Local Platform] Getting status for Living Room Lamp 3
[9/21/2018, 7:35:24 AM] [Insteon Local Platform] Received command for 1D51BE
[9/21/2018, 7:35:24 AM] [Insteon Local Platform] Found 1 accessories matching 1D51BE
[9/21/2018, 7:35:24 AM] [Insteon Local Platform] Hub command: {"standard":{"type":"50","id":"1D51BE","gatewayId":"4D6EE4","extended":false,"messageType":3,"hopsLeft":0,"maxHops":0,"command1":"11","command2":"1B","raw":"02501D51BE4D6EE460111B"}}
[9/21/2018, 7:35:24 AM] [Insteon Local Platform] Got event for Game Room Fan Light
[9/21/2018, 7:35:24 AM] [Insteon Local Platform] Got on event for Game Room Fan Light
[9/21/2018, 7:35:24 AM] [Insteon Local Platform] Received command for 3E8067
[9/21/2018, 7:35:24 AM] [Insteon Local Platform] Found 1 accessories matching 3E8067
[9/21/2018, 7:35:24 AM] [Insteon Local Platform] Hub command: {"standard":{"type":"50","id":"3E8067","gatewayId":"4D6EE4","extended":false,"messageType":3,"hopsLeft":0,"maxHops":0,"command1":"11","command2":"1B","raw":"02503E80674D6EE460111B"}}
[9/21/2018, 7:35:24 AM] [Insteon Local Platform] Got event for Game Room Lamp
[9/21/2018, 7:35:24 AM] [Insteon Local Platform] Got on event for Game Room Lamp
[9/21/2018, 7:35:24 AM] [Insteon Local Platform] Getting status for Living Room Lamp 1
[9/21/2018, 7:35:24 AM] [Insteon Local Platform] Getting status for Living Room Lamp 2
[9/21/2018, 7:35:24 AM] [Insteon Local Platform] Received command for 428940
[9/21/2018, 7:35:24 AM] [Insteon Local Platform] Found 1 accessories matching 428940
[9/21/2018, 7:35:24 AM] [Insteon Local Platform] Hub command: {"standard":{"type":"50","id":"428940","gatewayId":"4D6EE4","extended":false,"messageType":3,"hopsLeft":0,"maxHops":0,"command1":"11","command2":"1B","raw":"02504289404D6EE460111B"}}
[9/21/2018, 7:35:24 AM] [Insteon Local Platform] Got event for Keagan Room
[9/21/2018, 7:35:24 AM] [Insteon Local Platform] Got on event for Keagan Room
[9/21/2018, 7:35:24 AM] [Insteon Local Platform] Getting status for Living Room Fan Light
[9/21/2018, 7:35:24 AM] [Insteon Local Platform] Getting status for Dining Room
[9/21/2018, 7:35:24 AM] [Insteon Local Platform] Received command for 1DFA0B
[9/21/2018, 7:35:24 AM] [Insteon Local Platform] Found 2 accessories matching 1DFA0B
[9/21/2018, 7:35:24 AM] [Insteon Local Platform] Hub command: {"standard":{"type":"50","id":"1DFA0B","gatewayId":"4D6EE4","extended":false,"messageType":3,"hopsLeft":1,"maxHops":1,"command1":"11","command2":"1B","raw":"02501DFA0B4D6EE465111B"}}
[9/21/2018, 7:35:24 AM] [Insteon Local Platform] Got event for Bedroom Fan Light
[9/21/2018, 7:35:24 AM] [Insteon Local Platform] Got on event for Bedroom Fan Light
[9/21/2018, 7:35:24 AM] [Insteon Local Platform] Got event for All Off
[9/21/2018, 7:35:24 AM] [Insteon Local Platform] Got updated status for All Off
[9/21/2018, 7:35:24 AM] [Insteon Local Platform] Getting status for All Off
[9/21/2018, 7:35:25 AM] [Insteon Local Platform] Received command for 32B6B4
[9/21/2018, 7:35:25 AM] [Insteon Local Platform] Found 1 accessories matching 32B6B4
[9/21/2018, 7:35:25 AM] [Insteon Local Platform] Hub command: {"standard":{"type":"50","id":"32B6B4","gatewayId":"4D6EE4","extended":false,"messageType":3,"hopsLeft":1,"maxHops":1,"command1":"11","command2":"1B","raw":"025032B6B44D6EE465111B"}}
[9/21/2018, 7:35:25 AM] [Insteon Local Platform] Got event for Bedroom Lamp 2
[9/21/2018, 7:35:25 AM] [Insteon Local Platform] Got on event for Bedroom Lamp 2
[9/21/2018, 7:35:25 AM] [Insteon Local Platform] Received command for 4B1FFC
[9/21/2018, 7:35:25 AM] [Insteon Local Platform] Found 1 accessories matching 4B1FFC
[9/21/2018, 7:35:25 AM] [Insteon Local Platform] Hub command: {"standard":{"type":"50","id":"4B1FFC","gatewayId":"4D6EE4","extended":false,"messageType":3,"hopsLeft":0,"maxHops":0,"command1":"11","command2":"1B","raw":"02504B1FFC4D6EE460111B"}}
[9/21/2018, 7:35:25 AM] [Insteon Local Platform] Got event for Avery Room
[9/21/2018, 7:35:25 AM] [Insteon Local Platform] Got on event for Avery Room
[9/21/2018, 7:35:25 AM] [Insteon Local Platform] Getting status for Game Room Fan Light
[9/21/2018, 7:35:25 AM] [Insteon Local Platform] Getting status for Game Room Lamp
[9/21/2018, 7:35:25 AM] [Insteon Local Platform] Getting status for Keagan Room
[9/21/2018, 7:35:25 AM] [Insteon Local Platform] Getting status for All Off
/usr/local/lib/node_modules/homebridge-platform-insteonlocal/index.js:923
    self.light.level(function(err,level) {
               ^

TypeError: Cannot read property 'level' of undefined
    at InsteonLocalAccessory.getStatus (/usr/local/lib/node_modules/homebridge-platform-insteonlocal/index.js:923:16)
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-platform-insteonlocal/index.js:490:61)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)
iMac:~ jeffwhalen$

**Comment by jeffwhalen** [comment]
Config:
{ "name": "All Off",
								  "deviceID" : "1DFA0B",
								  "six_btn" : "true",
								  "keypadbtn" : "D",
								  "groupID" : "27",
								  "deviceType" : "scene" }

**Comment by jeffwhalen** [comment]
@kuestess I also noticed that the state of the scene isn't updated correctly even on home bridge reboot. If I changed "keypadbtn" to lower case "d" it correctly shows status on reboot. but don't update to the correct status after I trigger the scene in homebridge. Hope this helps. Thanks!

**Comment by kuestess** [comment]
@jeffwhalen Do you also have that device configured as a switch/dimmer/lightbulb?  For some reason, the event listener is calling the `getStatus` function intended for those devices, rather than a scene.

**Comment by kuestess** [comment]
@jeffwhalen It shouldn't cause an issue - let me do some testing on my end.

**Comment by shereefalkady** [comment]
@jeffwhalen @kuestess - the B doesn’t have to be capital ?

**Comment by jeffwhalen** [comment]
@shereefalkady @kuestess I thought the lower case letters worked, but now I’m not so sure. So I’ve changed them all back to capital.

**Comment by jeffwhalen** [comment]
@kuestess Ok, thanks I’ll give that a try tomorrow and let you know.

**Comment by jeffwhalen** [comment]
@kuestess I tried your recommendation of removal of "1DFA0b" and tried it again but I got the same outcome of it crashing homebridge. The only scenes i've been able to get to work for me is creating the scenes in the home kit app, the insteon scenes just aren't working for me.

**Comment by kuestess** [comment]
@jeffwhalen Just pushed a patch that I think should fix your issue with scenes crashing home bridge.  Give it a try and let me know if that takes care of it.

**Comment by jeffwhalen** [comment]
> @jeffwhalen Just pushed a patch that I think should fix your issue with scenes crashing home bridge. Give it a try and let me know if that takes care of it.

Just installed patch and gave it another try... but it crashed it again.

/usr/local/lib/node_modules/homebridge-platform-insteonlocal/index.js:919
    self.light.level(function(err,level) {
               ^

TypeError: Cannot read property 'level' of undefined
    at InsteonLocalAccessory.getStatus (/usr/local/lib/node_modules/homebridge-platform-insteonlocal/index.js:919:16)
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-platform-insteonlocal/index.js:490:61)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)

**Comment by kuestess** [comment]
@jeffwhalen Do you have any device types other than dimmer/lightbulb/switch in that scene?

**Comment by jeffwhalen** [comment]
> @jeffwhalen Do you have any device types other than dimmer/lightbulb/switch in that scene?

No their all dimmers, lightbulbs, and switches.The KPL I'm calling the scene from is older, not sure if thats causing the problem?

**Comment by kuestess** [comment]
@jeffwhalen Just uploaded a new version with some additional stuff to help debug - can you please run in debug mode (homebridge -D) and post the log from a crash?  Thanks!

**Comment by kuestess** [comment]
Closing due to inactivity.  Feel free to open another issue if this is not fixed.
