### ISSUE TITLE
Node 20.9 caused plugging to crash

### ISSUE THREAD

**Issue by btgh** [kuestess/homebridge-platform-insteonlocal#303]
Upgrading Node from 18.8 to 20.9 causes plugin to crash - reverting fixes it.

[20/11/2023, 13:01:27] [InsteonLocal] Connecting to Insteon PLM...

/var/lib/homebridge/node_modules/homebridge-platform-insteonlocal/node_modules/home-controller/lib/Insteon/index.js:123
    throw (new Error('serial is Unsupported on this platform'));
           ^
Error: serial is Unsupported on this platform
    at Insteon.serial (/var/lib/homebridge/node_modules/homebridge-platform-insteonlocal/node_modules/home-controller/lib/Insteon/index.js:123:12)
    at InsteonLocalPlatform.connectToHub (/var/lib/homebridge/node_modules/homebridge-platform-insteonlocal/src/InsteonLocalPlatform.ts:212:11)
    at new InsteonLocalPlatform (/var/lib/homebridge/node_modules/homebridge-platform-insteonlocal/src/InsteonLocalPlatform.ts:91:10)
    at ChildBridgeFork.startBridge (/var/lib/homebridge/node_modules/homebridge/src/childBridgeFork.ts:150:42)
[20/11/2023, 13:01:28] [InsteonLocal] Child bridge process ended
[20/11/2023, 13:01:28] [InsteonLocal] Process Ended. Code: 1, Signal: null
[20/11/2023, 13:01:35] [InsteonLocal] Restarting Process...
[20/11/2023, 13:01:37] [InsteonLocal] Launched child bridge with PID 6295
[20/11/2023, 13:01:38] Registering platform 'homebridge-platform-insteonlocal.InsteonLocal'
[20/11/2023, 13:01:38] [InsteonLocal] Loaded homebridge-platform-insteonlocal v0.5.11 child bridge successfully
[20/11/2023, 13:01:38] Loaded 16 cached accessories from cachedAccessories.0E53AC447644.
[20/11/2023, 13:01:38] [InsteonLocal] Connecting to Insteon PLM...

**Comment by kuestess** [comment]
@btgh This is an error from the serialport dependency - its been a pain in the butt.  You should be able to reinstall serialport via `npm i -g serialport` to fix it.
