### ISSUE TITLE
Continuous errors after trying multiple fixes

### ISSUE THREAD

**Issue by slack8182** [kuestess/homebridge-platform-insteonlocal#44]
Hey Kuestess,

After browsing through all the open and closed issues I’m still unable to get my hub to connect. I uninstalled and reinstalled. I’ve done a network reset on my hub. I’ve tried changing my port number, all to no avail. Here are my settings and my log. Any help from anybody would be greatly appreciated. 

platform": "InsteonLocal",
		    "name": "Insteon Local Platform",
				  "user": "slack8181",
				  "pass": "*******",
				  "host": "10.0.1.3",
				  "port": "25105",
				  "model": "2245",
				  "refresh":"300",
				  "server_port": "3003",
				  "keepAlive": "3600",

43:59] [Insteon Local Platform] Initializing InsteonLocal platform...
Nov 28 19:43:59 raspberrypi homebridge[32307]: [2018-11-28 19:43:59] [Insteon Local Platform] Started connection watcher...
Nov 28 19:43:59 raspberrypi homebridge[32307]: [2018-11-28 19:43:59] [Insteon Local Platform] Found 5 devices in config
Nov 28 19:43:59 raspberrypi homebridge[32307]: [2018-11-28 19:43:59] [Insteon Local Platform] Initializing platform accessory 'Bedroom Fan'...
Nov 28 19:43:59 raspberrypi homebridge[32307]: [2018-11-28 19:43:59] [Insteon Local Platform] Initializing platform accessory 'Living Room Light'...
Nov 28 19:43:59 raspberrypi homebridge[32307]: [2018-11-28 19:43:59] [Insteon Local Platform] Initializing platform accessory 'Bedroom Fan Light'...
Nov 28 19:43:59 raspberrypi homebridge[32307]: [2018-11-28 19:43:59] [Insteon Local Platform] Initializing platform accessory 'Bedroom Scentsy'...
Nov 28 19:43:59 raspberrypi homebridge[32307]: [2018-11-28 19:43:59] [Insteon Local Platform] Initializing platform accessory 'Kitchen Lights'...
 
Then when I try to turn on a light I get this error:
19:44:48] [Insteon Local Platform] Setting power state of Living Room Light to on
Nov 28 19:44:58 raspberrypi homebridge[32307]: [2018-11-28 19:44:58] [Insteon Local Platform] Error setting level of Living Room Light
Nov 28 19:44:58 raspberrypi homebridge[32307]: [2018-11-28 19:44:58] [Insteon Local Platform] Getting status for Living Room Light

**Comment by kuestess** [comment]
@slack8182 Is the user/pass the one from the underside of the hub (or from Settings->House in the Insteon app if you've changed it)?  You should use this user/pass and NOT the one that you use to login to the Insteon app.  From your log, its clear that the errors are because it is not connecting to the hub.

**Comment by slack8182** [comment]
My user/pass is the one I created myself in the Insteon app under "Settings"-"House"-"username" and "password". Should I use the user/pass that's under my hub?

**Comment by kuestess** [comment]
Yes, that's the correct password to use (from the app if you've set it).  Try running the node script below, substituting in the appropriate values for your hub in config.  Put the ID for one of your devices in insteonID.  When you run the script, you should get the connected to hub message in the console and the device specified should beep.  Just a simple test to see if you can connect to the hub.

var Insteon = require('home-controller').Insteon;
var util = require('util')

var hub = new Insteon();
var insteon = hub 

var config = {
  host: '[IP]',
  port: [port],
  user: '[user]',
  password: '[pass]'
};

var insteonID = '2E5D60'

hub.httpClient(config, function () {
  	console.log('Connected to Hub')

	hub.beep(insteonID, function(status){
		console.log('Status: ' + util.inspect(status))		
	})
})

**Comment by slack8182** [comment]
Here's what I'm getting

module.js:545    throw err;
    ^

Error: Cannot find module 'home-controller'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:470:25)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pi/test.js:1:77)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)

Thanks for the help

**Comment by kuestess** [comment]
@slack8182 You need to install home-controller.  Type `npm -g install home-controller` and then give it a try.

**Comment by slack8182** [comment]
I did and same exact error. Don’t know if this makes a difference but recently my old hub blew up. So I bought a new one and contacted Insteon support and I authorized them to delete my account so I could add my accessories. I had to create a new account and re register all my devices. Everything works just fine on my Insteon app though

**Comment by kuestess** [comment]
@slack8182 New hub shouldn't matter, as long as it is working with the Insteon app (sounds like it is).  Since you're still getting the error after installing home-controller, it seems like a path problem.  Not sure which OS you're running, but try adding the node directory to your path.

**Comment by camrun91** [comment]
I had to use the username and password on the bottom of the hub ignorer for this to work. I am not having any issues after updating that and the model of the hub in the config.

**Comment by kuestess** [comment]
Closing due to inactivity.
