### ISSUE TITLE
UI failure

### ISSUE THREAD

**Issue by xc99tour** [kuestess/homebridge-platform-insteonlocal#72]
In the UI, when I tap on Hub, I receive this:

TypeError: Cannot read property 'id' of undefined
    at /usr/local/lib/node_modules/homebridge-platform-insteonlocal/insteon-ui.js:2509:35
    at Array.forEach (<anonymous>)
    at InsteonUI.buildHubSceneData (/usr/local/lib/node_modules/homebridge-platform-insteonlocal/insteon-ui.js:2506:12)
    at InsteonUI.renderHubPage (/usr/local/lib/node_modules/homebridge-platform-insteonlocal/insteon-ui.js:233:7)
    at InsteonUI.handleRequest (/usr/local/lib/node_modules/homebridge-platform-insteonlocal/insteon-ui.js:1587:9)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/homebridge-platform-insteonlocal/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/local/lib/node_modules/homebridge-platform-insteonlocal/node_modules/express/lib/router/index.js:317:13)
    at /usr/local/lib/node_modules/homebridge-platform-insteonlocal/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/local/lib/node_modules/homebridge-platform-insteonlocal/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/local/lib/node_modules/homebridge-platform-insteonlocal/node_modules/express/lib/router/index.js:275:10)

**Comment by xc99tour** [comment]
I went to Devices, tapped on one of my devices, then tapped on Get Links.  Now when I tap on that specific device, I get this:

TypeError: Cannot read property 'id' of undefined
    at /usr/local/lib/node_modules/homebridge-platform-insteonlocal/insteon-ui.js:893:34
    at Array.forEach (<anonymous>)
    at buildDeviceLinkTable (/usr/local/lib/node_modules/homebridge-platform-insteonlocal/insteon-ui.js:886:44)
    at InsteonUI.renderDevicePage (/usr/local/lib/node_modules/homebridge-platform-insteonlocal/insteon-ui.js:554:4)
    at InsteonUI.handleRequest (/usr/local/lib/node_modules/homebridge-platform-insteonlocal/insteon-ui.js:1904:10)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/homebridge-platform-insteonlocal/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/local/lib/node_modules/homebridge-platform-insteonlocal/node_modules/express/lib/router/index.js:317:13)
    at /usr/local/lib/node_modules/homebridge-platform-insteonlocal/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/local/lib/node_modules/homebridge-platform-insteonlocal/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/local/lib/node_modules/homebridge-platform-insteonlocal/node_modules/express/lib/router/index.js:275:10)

**Comment by kuestess** [comment]
@xc99tour Working on the first error, do you have any groups (scenes) defined in the Insteon Hub app?  For some reason that array is ending up empty after all of the device<->hub links are filtered out.

**Comment by xc99tour** [comment]
Yes, several. What can I send you to help you diagnose what is going on?

**Comment by kuestess** [comment]
@xc99tour Can you upload your insteon.json?  That would help figure it out.  You might also try to rename it and then reload the plugin.  Go to the Hub page and click get hub info to see if that works.

**Comment by xc99tour** [comment]
Here is insteon.json, before and after. Deleting the old version fixed the issue! (both).  
[insteon.json.new.txt](https://github.com/kuestess/homebridge-platform-insteonlocal/files/3365885/insteon.json.new.txt)

[insteon.json.txt](https://github.com/kuestess/homebridge-platform-insteonlocal/files/3365882/insteon.json.txt)

**Comment by xc99tour** [comment]
It didn't solve my other issue of not catching events from my 6 button switch (issue 71).

Thank you for looking a this!

**Comment by kuestess** [comment]
Released 0.4.2 to fix this.
