### ISSUE TITLE
insteon.json not created

### ISSUE THREAD

**Issue by ctgreybeard** [kuestess/homebridge-platform-insteonlocal#75]
I was looking through the logs today and I saw that the `insteon.json` file was created so I went looking for it. It's not there. I run a non-standard config with `config.json` in a non-standard place. I tried creating a `.homebridge` directory in my home dir but that didn't fix it.  

I'm seeing a `No devices in config` message but it isn't clear where that is coming from.

Here's the start of my log:

```
Starting homebridge! 20190913-084104
[9/13/2019, 8:41:07 AM] Loaded config.json with 1 accessories and 2 platforms.
[9/13/2019, 8:41:07 AM] ---
[9/13/2019, 8:41:10 AM] Loaded plugin: homebridge-camera-ffmpeg
[9/13/2019, 8:41:10 AM] Registering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'
[9/13/2019, 8:41:10 AM] ---
[9/13/2019, 8:41:10 AM] Loaded plugin: homebridge-dummy
[9/13/2019, 8:41:10 AM] Registering accessory 'homebridge-dummy.DummySwitch'
[9/13/2019, 8:41:10 AM] ---
[9/13/2019, 8:41:10 AM] Loaded plugin: homebridge-ifttt
[9/13/2019, 8:41:10 AM] Registering platform 'homebridge-ifttt.IFTTT'
[9/13/2019, 8:41:10 AM] ---
[9/13/2019, 8:41:12 AM] Loaded plugin: homebridge-platform-insteonlocal
homebridge API version: 2.4
[9/13/2019, 8:41:12 AM] Registering platform 'homebridge-platform-insteonlocal.InsteonLocal'
[9/13/2019, 8:41:12 AM] ---
[9/13/2019, 8:41:13 AM] Loaded plugin: homebridge-weather-plus
[9/13/2019, 8:41:17 AM] Registering platform 'homebridge-weather-plus.WeatherPlus'
[9/13/2019, 8:41:17 AM] ---
[9/13/2019, 8:41:17 AM] Loading 2 platforms...
[9/13/2019, 8:41:17 AM] [Camera-ffmpeg] Initializing Camera-ffmpeg platform...
[9/13/2019, 8:41:17 AM] [InsteonLocal] Initializing InsteonLocal platform...
Initializing Insteon UI
Reading config from /Users/homebridge/Homebridge/etc/config.json
Found 2 platform(s) in config
Creating new insteon.json
No devices in config
[9/13/2019, 8:41:17 AM] [InsteonLocal] Started connection watcher...
[9/13/2019, 8:41:17 AM] [InsteonLocal] Found 23 devices in config
[9/13/2019, 8:41:17 AM] [InsteonLocal] Initializing platform accessory 'Deck Ctl'...
[9/13/2019, 8:41:17 AM] [InsteonLocal] Initializing platform accessory 'LR Lamp'...
[9/13/2019, 8:41:17 AM] [InsteonLocal] Initializing platform accessory 'Garden Window'...
[9/13/2019, 8:41:17 AM] [InsteonLocal] Initializing platform accessory 'MBR Lamp'...
[9/13/2019, 8:41:17 AM] [InsteonLocal] Initializing platform accessory 'Driveway Pole'...
[9/13/2019, 8:41:17 AM] [InsteonLocal] Initializing platform accessory 'Deck Main'...
[9/13/2019, 8:41:17 AM] [InsteonLocal] Initializing platform accessory 'Walkway'...
[9/13/2019, 8:41:17 AM] [InsteonLocal] Initializing platform accessory 'Front Door'...
[9/13/2019, 8:41:17 AM] [InsteonLocal] Initializing platform accessory 'DR Tree'...
[9/13/2019, 8:41:17 AM] [InsteonLocal] Initializing platform accessory 'Upstairs hall'...
[9/13/2019, 8:41:17 AM] [InsteonLocal] Initializing platform accessory 'DR Light'...
[9/13/2019, 8:41:17 AM] [InsteonLocal] Initializing platform accessory 'LR Main'...
[9/13/2019, 8:41:17 AM] [InsteonLocal] Initializing platform accessory 'MBR #1'...
```

**Comment by kuestess** [comment]
@ctgreybeard Have you used the ui to get hub and device info?  This looks like the message that comes up if there's no existing insteon.json.  The 'no devices....' is referring to the insteon.json.  If you get hub and device info in the ui, you should see that message change on the next startup.

**Comment by ctgreybeard** [comment]
I have express turned off if that's what you mean. Could I just create an empty insteon.json in the same place config.json is? And why, if it says it is creating the file, the file isn't created?

**Comment by kuestess** [comment]
@ctgreybeard With release 0.4, I added a web UI for managing devices/scenes/config, etc.  Point your browser to your homebridge host @port 3000 (by default, or whatever you might have specified in the config).  From there, you can click get hub info and get devices, which will save your hub/device config to insteon.json.  The function I use to create the insteon.json (if it doesn't exist) creates it in memory only, but doesn't save to disk until there is hub/device information to populate.

**Comment by ctgreybeard** [comment]
There is nothing listening on port 3000 or 3333 (see below).

The relevant part of my config (I hope) is:

```
      "model": "2413",
      "host": "/dev/cu.usbserial-A60089QK",
      "platform": "InsteonLocal",
      "refresh": "3600",
      "server_port": "3333",
      "use_express": false
```

At startup my log says:
```
[9/13/2019, 1:53:48 PM] [InsteonLocal] Initializing InsteonLocal platform...
Initializing Insteon UI
Reading config from /Users/homebridge/Homebridge/etc/config.json
Found 3 platform(s) in config
Creating new insteon.json
No devices in config
[9/13/2019, 1:53:48 PM] [InsteonLocal] Started connection watcher...
[9/13/2019, 1:53:48 PM] [InsteonLocal] Found 23 devices in config
[9/13/2019, 1:53:48 PM] [InsteonLocal] Initializing platform accessory 'Deck Ctl'...
[9/13/2019, 1:53:48 PM] [InsteonLocal] Initializing platform accessory 'LR Lamp'...
.
.
.
```

What did I do wrong?

**Comment by THX723** [comment]
You did not enable the Express server:
` "use_express": false`

Set to true.

**Comment by ctgreybeard** [comment]
OK, I enabled it. Made some changes using the UI, restarted HB and got this:

```
[9/14/2019, 12:58:37 PM] Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: b9b40aed-c4
    at Bridge.Accessory.addBridgedAccessory (/Users/homebridge/Homebridge/bin/node_modules/hap-nodejs/lib/Accessory.js:268:
    at Server.<anonymous> (/Users/homebridge/Homebridge/bin/node_modules/homebridge/lib/server.js:416:24)
    at /Users/homebridge/Homebridge/bin/node_modules/hap-nodejs/lib/util/once.js:16:19
    at InsteonLocalPlatform.accessories (/Users/homebridge/Homebridge/bin/node_modules/homebridge-platform-insteonlocal/ind
    at Server._loadPlatformAccessories (/Users/homebridge/Homebridge/bin/node_modules/homebridge/lib/server.js:403:20)
    at Server._loadPlatforms (/Users/homebridge/Homebridge/bin/node_modules/homebridge/lib/server.js:341:16)
    at Server.run (/Users/homebridge/Homebridge/bin/node_modules/homebridge/lib/server.js:90:36)
    at module.exports (/Users/homebridge/Homebridge/bin/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/Users/homebridge/Homebridge/bin/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:805:30)
```

I'll take a look at it more closely to see if it would be useful.  

Here's my config.json
[config.zip](https://github.com/kuestess/homebridge-platform-insteonlocal/files/3612959/config.zip)

**Comment by kuestess** [comment]
@ctgreybeard That error usually means that you have two devices with the same name.  Quick glance at your config and it looks like 'Deck Ctl' is a duplicate.  Under inactive, but home bridge may be trying to load it.

**Comment by ctgreybeard** [comment]
Well, it only failed after I saved the config that the UI created. But I've addressed the original problem and so I will close this until I get time to dig further into it. If I want to use the UI then I will probably need to do a little refactoring of my setup.

Thanks for the support!
