### ISSUE TITLE
Crashing Homebridge when no device is specified

### ISSUE THREAD

**Issue by borger** [kuestess/homebridge-platform-insteonlocal#77]
Hello, 

Amazing work on this repo! Congrats!

I was giving it a try, and I'm getting the following error message:

```
2019-10-05T19:43:38.788Z serialport:binding:auto-detect loading LinuxBinding
Sat, 05 Oct 2019 19:43:39 GMT express:application set "x-powered-by" to true
Sat, 05 Oct 2019 19:43:39 GMT express:application set "etag" to 'weak'
Sat, 05 Oct 2019 19:43:39 GMT express:application set "etag fn" to [Function: generateETag]
Sat, 05 Oct 2019 19:43:39 GMT express:application set "env" to 'development'
Sat, 05 Oct 2019 19:43:39 GMT express:application set "query parser" to 'extended'
Sat, 05 Oct 2019 19:43:39 GMT express:application set "query parser fn" to [Function: parseExtendedQueryString]
Sat, 05 Oct 2019 19:43:39 GMT express:application set "subdomain offset" to 2
Sat, 05 Oct 2019 19:43:39 GMT express:application set "trust proxy" to false
Sat, 05 Oct 2019 19:43:39 GMT express:application set "trust proxy fn" to [Function: trustNone]
Sat, 05 Oct 2019 19:43:39 GMT express:application booting in development mode
Sat, 05 Oct 2019 19:43:39 GMT express:application set "view" to [Function: View]
Sat, 05 Oct 2019 19:43:39 GMT express:application set "views" to '/var/homebridge/views'
Sat, 05 Oct 2019 19:43:39 GMT express:application set "jsonp callback name" to 'callback'
Sat, 05 Oct 2019 19:43:40 GMT express:router use '/' query
Sat, 05 Oct 2019 19:43:40 GMT express:router:layer new '/'
Sat, 05 Oct 2019 19:43:40 GMT express:router use '/' expressInit
Sat, 05 Oct 2019 19:43:40 GMT express:router:layer new '/'
Sat, 05 Oct 2019 19:43:40 GMT express:router:route new '/light/:id/on'
Sat, 05 Oct 2019 19:43:40 GMT express:router:layer new '/light/:id/on'
Sat, 05 Oct 2019 19:43:40 GMT express:router:route get '/light/:id/on'
Sat, 05 Oct 2019 19:43:40 GMT express:router:layer new '/'
Sat, 05 Oct 2019 19:43:40 GMT express:router:route new '/light/:id/off'
Sat, 05 Oct 2019 19:43:40 GMT express:router:layer new '/light/:id/off'
Sat, 05 Oct 2019 19:43:40 GMT express:router:route get '/light/:id/off'
Sat, 05 Oct 2019 19:43:40 GMT express:router:layer new '/'
Sat, 05 Oct 2019 19:43:40 GMT express:router:route new '/light/:id/status'
Sat, 05 Oct 2019 19:43:40 GMT express:router:layer new '/light/:id/status'
Sat, 05 Oct 2019 19:43:40 GMT express:router:route get '/light/:id/status'
Sat, 05 Oct 2019 19:43:40 GMT express:router:layer new '/'
Sat, 05 Oct 2019 19:43:40 GMT express:router:route new '/light/:id/level/:targetLevel'
Sat, 05 Oct 2019 19:43:40 GMT express:router:layer new '/light/:id/level/:targetLevel'
Sat, 05 Oct 2019 19:43:40 GMT express:router:route get '/light/:id/level/:targetLevel'
Sat, 05 Oct 2019 19:43:40 GMT express:router:layer new '/'
Sat, 05 Oct 2019 19:43:40 GMT express:router:route new '/scene/:group/on'
Sat, 05 Oct 2019 19:43:40 GMT express:router:layer new '/scene/:group/on'
Sat, 05 Oct 2019 19:43:40 GMT express:router:route get '/scene/:group/on'
Sat, 05 Oct 2019 19:43:40 GMT express:router:layer new '/'
Sat, 05 Oct 2019 19:43:40 GMT express:router:route new '/scene/:group/off'
Sat, 05 Oct 2019 19:43:40 GMT express:router:layer new '/scene/:group/off'
Sat, 05 Oct 2019 19:43:40 GMT express:router:route get '/scene/:group/off'
Sat, 05 Oct 2019 19:43:40 GMT express:router:layer new '/'
Sat, 05 Oct 2019 19:43:40 GMT express:router:route new '/links'
Sat, 05 Oct 2019 19:43:40 GMT express:router:layer new '/links'
Sat, 05 Oct 2019 19:43:40 GMT express:router:route get '/links'
Sat, 05 Oct 2019 19:43:40 GMT express:router:layer new '/'
Sat, 05 Oct 2019 19:43:40 GMT express:router:route new '/links/:id'
Sat, 05 Oct 2019 19:43:40 GMT express:router:layer new '/links/:id'
Sat, 05 Oct 2019 19:43:40 GMT express:router:route get '/links/:id'
Sat, 05 Oct 2019 19:43:40 GMT express:router:layer new '/'
Sat, 05 Oct 2019 19:43:40 GMT express:router:route new '/info/:id'
Sat, 05 Oct 2019 19:43:40 GMT express:router:layer new '/info/:id'
Sat, 05 Oct 2019 19:43:40 GMT express:router:route get '/info/:id'
Sat, 05 Oct 2019 19:43:40 GMT express:router:layer new '/'
Sat, 05 Oct 2019 19:43:40 GMT express:router:route new '/iolinc/:id/relay_on'
Sat, 05 Oct 2019 19:43:40 GMT express:router:layer new '/iolinc/:id/relay_on'
Sat, 05 Oct 2019 19:43:40 GMT express:router:route get '/iolinc/:id/relay_on'
Sat, 05 Oct 2019 19:43:40 GMT express:router:layer new '/'
Sat, 05 Oct 2019 19:43:40 GMT express:router:route new '/iolinc/:id/relay_off'
Sat, 05 Oct 2019 19:43:40 GMT express:router:layer new '/iolinc/:id/relay_off'
Sat, 05 Oct 2019 19:43:40 GMT express:router:route get '/iolinc/:id/relay_off'
Sat, 05 Oct 2019 19:43:40 GMT express:router:layer new '/'
Sat, 05 Oct 2019 19:43:40 GMT express:router:route new '/iolinc/:id/sensor_status'
Sat, 05 Oct 2019 19:43:40 GMT express:router:layer new '/iolinc/:id/sensor_status'
Sat, 05 Oct 2019 19:43:40 GMT express:router:route get '/iolinc/:id/sensor_status'
Sat, 05 Oct 2019 19:43:40 GMT express:router:layer new '/'
Sat, 05 Oct 2019 19:43:40 GMT express:router:route new '/iolinc/:id/relay_status'
Sat, 05 Oct 2019 19:43:40 GMT express:router:layer new '/iolinc/:id/relay_status'
Sat, 05 Oct 2019 19:43:40 GMT express:router:route get '/iolinc/:id/relay_status'
Sat, 05 Oct 2019 19:43:40 GMT express:router:layer new '/'
Sat, 05 Oct 2019 19:43:40 GMT express:router use '/' <anonymous>
Sat, 05 Oct 2019 19:43:40 GMT express:router:layer new '/'
[10/5/2019, 4:43:40 PM] TypeError: Cannot read property 'length' of undefined
    at new InsteonLocalPlatform (/usr/local/lib/node_modules/homebridge-platform-insteonlocal/index.js:292:35)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:337:32)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:90:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
```
Any ideas what is going on? The same error happened when I had none devices and after I've added one device, could that be causing this?

Here's my config, on the config.json:
```
[...]
"platforms": [
    {
      "platform": "InsteonLocal",
      "name": "Insteon Local Platform",
      "user": "<myuser>",
      "pass": "<mypassword>",
      "host": "<myip>",
      "port": "25105",
      "model": "2245",
      "refresh":"0",
      "server_port": "3000",
      "keepAlive": "3600"
    },
[...]
```

I was able to connect manually with the same credentials using the home-controller directly, with basically this code:
```
var Insteon = require('home-controller').Insteon;
var insteon = new Insteon();
var config = {
  host: '<myip>',
  port: 25105,
  user: '<myuser>',
  password: '<mypassword>'
};
insteon.httpClient(config, function(){
  console.log('Connected!');
});
```
So I've ruled credentials/connectivity out of the way... Any suggestions will be greatly appreciated!

Thanks,

borger

**Comment by borger** [comment]
Nevermind, my mistake, I just saw that I have to inform the devices in the config as well. 

To anyone who had the same mistake, make sure you inform the devices on your config.json file like so:

```
[...]
{
      "platform": "InsteonLocal",
      "name": "Insteon Local Platform",
      "user": "<myuser>",
      "pass": "<mypassword>",
      "host": "<myip>",
      "port": "25105",
      "model": "2245",
      "refresh":"0",
      "server_port": "3000",
      "keepAlive": "3600",
      "devices": [
        { 
	  "name": "Living Room Lights",
 	  "deviceID" : "<deviceid>",
  	  "dimmable" : "no",
 	  "deviceType" : "lightbulb" 
        }]
        [...]
    },
[...]
```

**Comment by borger** [comment]
However it was crashing homebridge because of that, maybe that's something I could help fix, I'll reopen the issue and look at the code..
