### ISSUE TITLE
Can't find serial port when PLM directly connected to a Ubuntu box

### ISSUE THREAD

**Issue by pashdown** [kuestess/homebridge-platform-insteonlocal#84]
This is what I'm getting when I try to run this 2243 style on a Ubuntu box with the PLM directly connected.

[12/27/2019, 4:23:10 PM] Error: serial is Unsupported on this platform
    at Insteon.serial (/usr/local/lib/node_modules/homebridge-platform-insteonlocal/node_modules/home-controller/lib/Insteon/index.js:118:12)
    at InsteonLocalPlatform.connectToHub (/usr/local/lib/node_modules/homebridge-platform-insteonlocal/index.js:365:7)
    at new InsteonLocalPlatform (/usr/local/lib/node_modules/homebridge-platform-insteonlocal/index.js:299:7)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:337:32)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:90:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

**Comment by BlueiPhone** [comment]
When ever I point to http://192.168.1.96:25105/ it pops up with:

 



 

I enter the Username and Password from the back of the hub and I get this:

 



In the upper left corner of the screen…

 

This is a picture from the bottom of my hub:

 



 

I just wanted to give you a heads up…

 

Clay

**Comment by kuestess** [comment]
@pashdown I get this error too. Not sure why it happens. Change into your node directory, then node_modules/homebridge-platform-Insteon local/node_modules. From there, change into the serialport directory and then type ```
npm install``` and it should install no problem.

**Comment by kuestess** [comment]
@pashdown Assuming that you got this working.  If not, feel free to reopen.  Also, see #86.

**Comment by Jmakosky** [comment]
InsteonLocal has been installed for six months and working great.  I was gone for a week and came home to this error (further below) in my Homebridge log and I cannot figure it out:
Hardware=
MacOS - latest
MacMini M1
USB plugged into Insteon PLM (2413U?)
Latest Node.js and all plugins are up to date.
Also, I cannot access my InsteonUI any longer where it worked fine a month ago.  My Server Port was 3000 but it won't work.  I am wondering if my port changed?
Here is the error message:
---------------------------------
Error: serial is Unsupported on this platform
    at Insteon.serial (/usr/local/lib/node_modules/homebridge-platform-insteonlocal/node_modules/home-controller/lib/Insteon/index.js:123:12)
    at InsteonLocalPlatform.connectToHub (/usr/local/lib/node_modules/homebridge-platform-insteonlocal/src/InsteonLocalPlatform.ts:212:11)
    at new InsteonLocalPlatform (/usr/local/lib/node_modules/homebridge-platform-insteonlocal/src/InsteonLocalPlatform.ts:91:10)
    at ChildBridgeFork.startBridge (/usr/local/lib/node_modules/homebridge/src/childBridgeFork.ts:150:42)
[7/30/2023, 3:05:59 PM] [HB Insteon] Child bridge process ended
[7/30/2023, 3:05:59 PM] [HB Insteon] Process Ended. Code: 1, Signal: null
-------------------------------------------------
Any help would be appreciated.  I have reinstalled InsteonLocal but I am starting to get a little nervous I am going to mess it all up because it was working fine a week ago when I left for work.

**Comment by Jmakosky** [comment]
BY THE WAY - I tried my Indigodomo to see if it still worked with the PLM and it worked just fine.  So, the PLM is not the issue.

**Comment by kuestess** [comment]
@Jmakosky Its an issue with the serialport node package.  It's been a pain over the years.  Change directory into `/usr/local/lib/node_modules/homebridge-platform-insteonlocal/node_modules/home-controller/` delete the `serialport` and `@serialport` directories (if they exist), and then run `npm install serialport@latest`

**Comment by Jmakosky** [comment]
I believe I followed the instructions per above and this is now my error.  Good news is that it did change and seems like a more concise issue.  I rebooted the MacMini as well.  I feel like I am missing something obvious.  Excuse me for being a noob at this.  Any thoughts? 
I also attached a snipit of my Insteon hub settings from the plugin.  Thought maybe that might help diagnose.  This page added it as a link below - not sure if that works or not.  I did verify my path to the device so I know that is correct.

![Xnip2023-07-31_19-39-57](https://github.com/kuestess/homebridge-platform-insteonlocal/assets/36600675/22c5827a-b3e3-44e4-aaa1-30eccb63de2d)


------------------------------------------
Restarting Process...
[7/31/2023, 7:33:40 PM] [HB Insteon] Launched child bridge with PID 1077
[7/31/2023, 7:33:40 PM] Registering platform 'homebridge-platform-insteonlocal.InsteonLocal'
[7/31/2023, 7:33:40 PM] [HB Insteon] Loaded homebridge-platform-insteonlocal v0.5.10 child bridge successfully
[7/31/2023, 7:33:40 PM] Loaded 34 cached accessories from cachedAccessories.0E715EDDF1D9.

/usr/local/lib/node_modules/homebridge-platform-insteonlocal/node_modules/home-controller/lib/Insteon/index.js:153
  this.socket = new this.SerialPort(comName, this.options)
                ^
TypeError: this.SerialPort is not a constructor
    at Insteon.serial (/usr/local/lib/node_modules/homebridge-platform-insteonlocal/node_modules/home-controller/lib/Insteon/index.js:153:17)
    at InsteonLocalPlatform.connectToHub (/usr/local/lib/node_modules/homebridge-platform-insteonlocal/src/InsteonLocalPlatform.ts:212:11)
    at new InsteonLocalPlatform (/usr/local/lib/node_modules/homebridge-platform-insteonlocal/src/InsteonLocalPlatform.ts:91:10)
    at ChildBridgeFork.startBridge (/usr/local/lib/node_modules/homebridge/src/childBridgeFork.ts:150:42)
[7/31/2023, 7:33:40 PM] [HB Insteon] Child bridge process ended
[7/31/2023, 7:33:40 PM] [HB Insteon] Process Ended. Code: 1, Signal: null
----------------------------------------
I would appreciate any help at this point.

**Comment by kuestess** [comment]
@Jmakosky Looks like the `serialport` api changed between versions.  Back in that same directory, please delete the `serialport` and `@serialport` directories (again), and then run `npm install serialport@8.0.8`. This will install an older version of `serialport` (rather than latest) that uses the correct version of the api the `home-controller` package was written for.

**Comment by Jmakosky** [comment]
FYI - serialport and @serialport directories don't exist.  I just checked again to be sure.  I am up to your latest InsteonLocal version from a two days ago.
Just ran the install and here is the error - back to the original.  Should I just delete and reinstall everything?  I hate to add 34 devices again.  It was painful when I first did it but if that will get me up and running I am willing to do so.  If you agree then how do I totally clean off the existing plugin so the same error doesn't linger?

------------------------------------
Restarting Process...
[7/31/2023, 8:14:02 PM] [HB Insteon] Launched child bridge with PID 3498
[7/31/2023, 8:14:02 PM] Registering platform 'homebridge-platform-insteonlocal.InsteonLocal'
[7/31/2023, 8:14:02 PM] [HB Insteon] Loaded homebridge-platform-insteonlocal v0.5.10 child bridge successfully
[7/31/2023, 8:14:02 PM] Loaded 34 cached accessories from cachedAccessories.0E715EDDF1D9.

/usr/local/lib/node_modules/homebridge-platform-insteonlocal/node_modules/home-controller/lib/Insteon/index.js:123
    throw (new Error('serial is Unsupported on this platform'));
           ^
Error: serial is Unsupported on this platform
    at Insteon.serial (/usr/local/lib/node_modules/homebridge-platform-insteonlocal/node_modules/home-controller/lib/Insteon/index.js:123:12)
    at InsteonLocalPlatform.connectToHub (/usr/local/lib/node_modules/homebridge-platform-insteonlocal/src/InsteonLocalPlatform.ts:212:11)
    at new InsteonLocalPlatform (/usr/local/lib/node_modules/homebridge-platform-insteonlocal/src/InsteonLocalPlatform.ts:91:10)
    at ChildBridgeFork.startBridge (/usr/local/lib/node_modules/homebridge/src/childBridgeFork.ts:150:42)
[7/31/2023, 8:14:02 PM] [HB Insteon] Child bridge process ended
[7/31/2023, 8:14:02 PM] [HB Insteon] Process Ended. Code: 1, Signal: null

**Comment by kuestess** [comment]
@Jmakosky You shouldn't lose your config if you nuke and reinstall the plugin, but I think we can figure out where serialport is installed.  It's likely in one of the directories in that same hierarchy - change to `/usr/local/lib/node_modules/` to start with.  It won't likely be there (delete both if it is), but then change into the `homebridge-platform-insteonlocal/node_modules` sub-directory and you'll likely see it there.  Delete both `serialport` and `@serialport` and then reinstall 8.0.8 as above.

**Comment by Jmakosky** [comment]
Found @serialport under the nodes_module directory and deleted (rmdir) it.  Hunted all over for "serialport" directory or file and found nothing.
Executed the npm install serialport@8.0.8 command and @serialport came back - I assume reinstalled by the command.  Still no "serialport" directory or file anywhere.  
Restarted Homebridge using the "restart" button.  Just letting you know in case I am supposed to do it differently.
Below appears to be the same error.  

--------------------
Restarting Process..
[7/31/2023, 8:54:06 PM] [HB Insteon] Launched child bridge with PID 6323
[7/31/2023, 8:54:06 PM] Registering platform 'homebridge-platform-insteonlocal.InsteonLocal'
[7/31/2023, 8:54:06 PM] [HB Insteon] Loaded homebridge-platform-insteonlocal v0.5.10 child bridge successfully
[7/31/2023, 8:54:06 PM] Loaded 34 cached accessories from cachedAccessories.0E715EDDF1D9.

/usr/local/lib/node_modules/homebridge-platform-insteonlocal/node_modules/home-controller/lib/Insteon/index.js:123
    throw (new Error('serial is Unsupported on this platform'));
           ^
Error: serial is Unsupported on this platform
    at Insteon.serial (/usr/local/lib/node_modules/homebridge-platform-insteonlocal/node_modules/home-controller/lib/Insteon/index.js:123:12)
    at InsteonLocalPlatform.connectToHub (/usr/local/lib/node_modules/homebridge-platform-insteonlocal/src/InsteonLocalPlatform.ts:212:11)
    at new InsteonLocalPlatform (/usr/local/lib/node_modules/homebridge-platform-insteonlocal/src/InsteonLocalPlatform.ts:91:10)
    at ChildBridgeFork.startBridge (/usr/local/lib/node_modules/homebridge/src/childBridgeFork.ts:150:42)
[7/31/2023, 8:54:06 PM] [HB Insteon] Child bridge process ended
[7/31/2023, 8:54:06 PM] [HB Insteon] Process Ended. Code: 1, Signal: null

**Comment by kuestess** [comment]
@Jmakosky Well crud - if the surgical approach won't work, then we can try the nuclear option - ie, uninstall/reinstall.  First, run `npm unininstall -g homebridge-platform-insteonlocal`.  For safe keeping, run `npm unininstall -g serialport`.  Confirm that the `serialport` and `homebridge-platform-insteonlocal` directories are gone in `/usr/local/lib/node_modules/`.  If not, then delete them.  Next run `npm ininstall -g homebridge-platform-insteonlocal` and try to restart the plugin.  Your devices/config should be preserved.

**Comment by Jmakosky** [comment]
Will do.  Probably won't happen until this weekend.  The rest of the week is pretty full for me.
