### ISSUE TITLE
No support for serial connection

### ISSUE THREAD

**Issue by travisandkelly** [kuestess/homebridge-platform-insteonlocal#91]
This was working beautifully but now I'm getting this in the log:
`Initializing Insteon UI 
Reading config from /Users/theholts/.homebridge/config.json
Found 2 platform(s) in config
Creating new insteon.json
No devices in config
[2/29/2020, 9:05:53 AM] Error: serial is Unsupported on this platform
    at Insteon.serial (/usr/local/lib/node_modules/homebridge-platform-insteonlocal/node_modules/home-controller/lib/Insteon/index.js:118:12)
    at InsteonLocalPlatform.connectToHub (/usr/local/lib/node_modules/homebridge-platform-insteonlocal/index.js:401:7)
    at new InsteonLocalPlatform (/usr/local/lib/node_modules/homebridge-platform-insteonlocal/index.js:299:7)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:337:32)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:90:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
[2/29/2020, 9:05:53 AM] Got SIGTERM, shutting down Homebridge...
[2/29/2020, 9:05:58 AM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null`

Here is my config:
`{
    "bridge": {
        "name": "Homebridge C23F",
        "username": "0E:E1:95:98:C2:3F",
        "port": 51670,
        "pin": "136-76-260"
    },
    "accessories": [],
    "platforms": [
        {
            "platform": "InsteonLocal",
            "name": "Insteon Local Platform",
            "host": "/dev/tty.usbserial-AL02YC85",
            "model": "plm",
            "devices": [
                {
                    "name": "Master Bedroom Lights",
                    "deviceID": "1D.24.06",
                    "dimmable": "yes",
                    "deviceType": "dimmer"
                },
                {
                    "name": "Living Room Lights",
                    "deviceID": "20.9D.B6",
                    "dimmable": "yes",
                    "deviceType": "dimmer"
                },
                {
                    "name": "Front Entrance Light",
                    "deviceID": "20.98.47",
                    "dimmable": "yes",
                    "deviceType": "dimmer"
                }
            ]
        },
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        }
    ]
}`
I tried to uninstall/reinstall but no luck.

**Comment by kuestess** [comment]
@travisandkelly This is a problem with the serialport package that home-controller depends on.  For whatever reason, home-controller still has the dependency as a very old version, which isn't supported on all platforms.  The newer version is.  You should be able to fix either by re-installing the plugin `npm -g install homebridge-platform-insteonlocal` (won't impact your config).  Let me know if that doesn't work.

**Comment by travisandkelly** [comment]
Here is the output from re-installing the plugin:
`The-Holts-iMac:~ theholts$ npm -g install homebridge-platform-insteonlocal
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

> serialport@6.2.2 install /usr/local/lib/node_modules/homebridge-platform-insteonlocal/node_modules/serialport
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=12.16.1 runtime=node arch=x64 platform=darwin)
  CXX(target) Release/obj.target/serialport/src/serialport.o
../src/serialport.cpp:41:39: error: no matching member function for call to 'ToString'
  v8::String::Utf8Value path(info[0]->ToString());
                             ~~~~~~~~~^~~~~~~~
/Users/theholts/Library/Caches/node-gyp/12.16.1/include/node/v8.h:2668:44: note: candidate function not viable: requires single argument 'context', but no
      arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<String> ToString(
                                           ^
/Users/theholts/Library/Caches/node-gyp/12.16.1/include/node/v8.h:2684:31: note: candidate function not viable: requires single argument 'isolate', but no
      arguments were provided
                Local<String> ToString(Isolate* isolate) const);
                              ^
../src/serialport.cpp:48:44: error: no matching member function for call to 'ToObject'
  v8::Local<v8::Object> options = info[1]->ToObject();
                                  ~~~~~~~~~^~~~~~~~
/Users/theholts/Library/Caches/node-gyp/12.16.1/include/node/v8.h:2672:44: note: candidate function not viable: requires single argument 'context', but no
      arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                           ^
/Users/theholts/Library/Caches/node-gyp/12.16.1/include/node/v8.h:2686:31: note: candidate function not viable: requires single argument 'isolate', but no
      arguments were provided
                Local<Object> ToObject(Isolate* isolate) const);
                              ^
../src/serialport.cpp:95:18: warning: 'Call' is deprecated [-Wdeprecated-declarations]
  data->callback.Call(2, argv);
                 ^
../../nan/nan.h:1739:3: note: 'Call' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
../../nan/nan.h:104:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/serialport.cpp:113:44: error: no matching member function for call to 'ToObject'
  v8::Local<v8::Object> options = info[1]->ToObject();
                                  ~~~~~~~~~^~~~~~~~
/Users/theholts/Library/Caches/node-gyp/12.16.1/include/node/v8.h:2672:44: note: candidate function not viable: requires single argument 'context', but no
      arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                           ^
/Users/theholts/Library/Caches/node-gyp/12.16.1/include/node/v8.h:2686:31: note: candidate function not viable: requires single argument 'isolate', but no
      arguments were provided
                Local<Object> ToObject(Isolate* isolate) const);
                              ^
../src/serialport.cpp:150:18: warning: 'Call' is deprecated [-Wdeprecated-declarations]
  data->callback.Call(1, argv);
                 ^
../../nan/nan.h:1739:3: note: 'Call' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
../../nan/nan.h:104:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/serialport.cpp:188:18: warning: 'Call' is deprecated [-Wdeprecated-declarations]
  data->callback.Call(1, argv);
                 ^
../../nan/nan.h:1739:3: note: 'Call' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
../../nan/nan.h:104:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/serialport.cpp:231:18: warning: 'Call' is deprecated [-Wdeprecated-declarations]
  data->callback.Call(1, argv);
                 ^
../../nan/nan.h:1739:3: note: 'Call' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
../../nan/nan.h:104:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/serialport.cpp:250:44: error: no matching member function for call to 'ToObject'
  v8::Local<v8::Object> options = info[1]->ToObject();
                                  ~~~~~~~~~^~~~~~~~
/Users/theholts/Library/Caches/node-gyp/12.16.1/include/node/v8.h:2672:44: note: candidate function not viable: requires single argument 'context', but no
      arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                           ^
/Users/theholts/Library/Caches/node-gyp/12.16.1/include/node/v8.h:2686:31: note: candidate function not viable: requires single argument 'isolate', but no
      arguments were provided
                Local<Object> ToObject(Isolate* isolate) const);
                              ^
../src/serialport.cpp:285:18: warning: 'Call' is deprecated [-Wdeprecated-declarations]
  data->callback.Call(1, argv);
                 ^
../../nan/nan.h:1739:3: note: 'Call' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
../../nan/nan.h:104:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/serialport.cpp:329:14: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
    results->Set(Nan::New<v8::String>("cts").ToLocalChecked(), Nan::New<v8::Boolean>(data->cts));
             ^
/Users/theholts/Library/Caches/node-gyp/12.16.1/include/node/v8.h:3498:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/theholts/Library/Caches/node-gyp/12.16.1/include/node/v8config.h:328:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/serialport.cpp:330:14: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
    results->Set(Nan::New<v8::String>("dsr").ToLocalChecked(), Nan::New<v8::Boolean>(data->dsr));
             ^
/Users/theholts/Library/Caches/node-gyp/12.16.1/include/node/v8.h:3498:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/theholts/Library/Caches/node-gyp/12.16.1/include/node/v8config.h:328:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/serialport.cpp:331:14: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
    results->Set(Nan::New<v8::String>("dcd").ToLocalChecked(), Nan::New<v8::Boolean>(data->dcd));
             ^
/Users/theholts/Library/Caches/node-gyp/12.16.1/include/node/v8.h:3498:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/theholts/Library/Caches/node-gyp/12.16.1/include/node/v8config.h:328:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/serialport.cpp:336:18: warning: 'Call' is deprecated [-Wdeprecated-declarations]
  data->callback.Call(2, argv);
                 ^
../../nan/nan.h:1739:3: note: 'Call' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
../../nan/nan.h:104:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/serialport.cpp:378:14: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
    results->Set(Nan::New<v8::String>("baudRate").ToLocalChecked(), Nan::New<v8::Integer>(data->baudRate));
             ^
/Users/theholts/Library/Caches/node-gyp/12.16.1/include/node/v8.h:3498:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/theholts/Library/Caches/node-gyp/12.16.1/include/node/v8config.h:328:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/serialport.cpp:383:18: warning: 'Call' is deprecated [-Wdeprecated-declarations]
  data->callback.Call(2, argv);
                 ^
../../nan/nan.h:1739:3: note: 'Call' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
../../nan/nan.h:104:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/serialport.cpp:424:18: warning: 'Call' is deprecated [-Wdeprecated-declarations]
  data->callback.Call(1, argv);
                 ^
../../nan/nan.h:1739:3: note: 'Call' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
../../nan/nan.h:104:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/serialport.cpp:460:8: error: variable has incomplete type 'void'
  void init(v8::Handle<v8::Object> target) {
       ^
../src/serialport.cpp:460:34: error: expected '(' for function-style cast or type construction
  void init(v8::Handle<v8::Object> target) {
                       ~~~~~~~~~~^
../src/serialport.cpp:460:17: error: no member named 'Handle' in namespace 'v8'
  void init(v8::Handle<v8::Object> target) {
            ~~~~^
../src/serialport.cpp:460:36: error: use of undeclared identifier 'target'
  void init(v8::Handle<v8::Object> target) {
                                   ^
../src/serialport.cpp:460:43: error: expected ';' after top level declarator
  void init(v8::Handle<v8::Object> target) {
                                          ^
                                          ;
12 warnings and 9 errors generated.
make: *** [Release/obj.target/serialport/src/serialport.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:311:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/homebridge-platform-insteonlocal/node_modules/serialport
gyp ERR! node -v v12.16.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! serialport@6.2.2 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the serialport@6.2.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/theholts/.npm/_logs/2020-02-29T17_09_50_000Z-debug.log
The-Holts-iMac:~ theholts$ `

**Comment by kuestess** [comment]
Interesting...still picking up the old version.  More than one way to go about it.  Change directory into `/usr/local/lib/node_modules/homebridge-platform-insteonlocal/node_modules/home-controller/`, delete the `serialport` and `@serialport` directories, and then run `npm install serialport@latest`

**Comment by travisandkelly** [comment]
Those files do not exist in this location even after `npm install serialport@latest`

**Comment by kuestess** [comment]
@travisandkelly Were they there before you deleted/reinstalled?  If not, from you log above, change directory to `/usr/local/lib/node_modules/homebridge-platform-insteonlocal/node_modules/` delete the `serialport` and `@serialport` directories, and then run `npm install serialport@latest`

**Comment by travisandkelly** [comment]
Got it working, thanks again!
